RundeeItemFactory: RundeeItemFactory/RundeeItemFactory/src/Validators/FoodItemValidator.cpp File Reference
FoodItemValidator.cpp File Reference
#include "Validators/FoodItemValidator.h"
#include "Utils/JsonUtils.h"
#include <iostream>
#include <algorithm>
#include <cctype>
#include <fstream>
#include <chrono>
Functions
static float ComputePower (const ItemFoodData &item)
static void EnsureFoodShape (ItemFoodData &item)
static void EnsureSpoilage (ItemFoodData &item)
static void EnsureRarity (ItemFoodData &item)
Function Documentation
ComputePower()
float ComputePower (const ItemFoodData & item) static
Definition at line 19 of file FoodItemValidator.cpp.
References ItemFoodData::healthRestore, ItemFoodData::hungerRestore, and ItemFoodData::thirstRestore.
Referenced by EnsureRarity().
EnsureFoodShape()
void EnsureFoodShape (ItemFoodData & item) static
Definition at line 27 of file FoodItemValidator.cpp.
References ItemDataBase::category, ItemFoodData::hungerRestore, and ItemFoodData::thirstRestore.
Referenced by FoodItemValidator::Validate().
EnsureRarity()
void EnsureRarity (ItemFoodData & item) static
Definition at line 63 of file FoodItemValidator.cpp.
References JsonUtils::ClampInt(), ComputePower(), ItemFoodData::healthRestore, ItemFoodData::hungerRestore, ItemDataBase::rarity, and ItemFoodData::thirstRestore.
EnsureSpoilage()
void EnsureSpoilage (ItemFoodData & item) static
Definition at line 48 of file FoodItemValidator.cpp.
References JsonUtils::ClampInt(), ItemFoodData::spoils, and ItemFoodData::spoilTimeMinutes.