RundeeItemFactory: RundeeItemFactory/RundeeItemFactory/src/Generators/ItemGenerator.cpp File Reference
ItemGenerator.cpp File Reference
#include "Generators/ItemGenerator.h"
#include "Helpers/CommandLineParser.h"
#include "Helpers/QualityChecker.h"
#include "Parsers/ItemJsonParser.h"
#include "Writers/ItemJsonWriter.h"
#include "Prompts/PromptBuilder.h"
#include "Prompts/CustomPreset.h"
#include "Clients/OllamaClient.h"
#include <map>
#include <json.hpp>
#include <iostream>
#include <fstream>
#include <set>
#include <iomanip>
#include <sstream>
#include <ctime>
#include <memory>
#include <chrono>
#include <algorithm>
#include <thread>
#include <future>
#include <mutex>
#include <functional>
#include <sys/stat.h>
Namespaces
namespace ItemGenerator
Main namespace for item generation functionality.
Functions
static void EnsureParentDir (const std::string &path)
static std::string GetRegistryPath (const std::string &typeName)
static std::set< std::string > LoadRegistryIds (const std::string &typeName)
static bool SaveRegistryIds (const std::string &typeName, const std::set< std::string > &ids)
static void LogRegistryEvent (const std::string &typeName, size_t beforeCount, size_t addedCount, size_t afterCount)
template<typename T>
static void AppendIdsToRegistry (const std::string &typeName, const std::vector< T > &items)
static std::string CleanJsonTrailingCommas (const std::string &text)
static bool SaveTextFile (const std::string &path, const std::string &text)
static std::string GetCurrentTimestamp ()
static int ProcessLLMResponse_Ammo (const std::string &jsonResponse, const std::string &outputPath, int requiredCount, const std::set< std::string > &excludeIds, const std::string &modelName, const FoodGenerateParams &params, PresetType preset, std::map< std::string, QualityChecker::QualityResult > &qualityResults)
static int ProcessLLMResponse_Drink (const std::string &jsonResponse, const std::string &outputPath, int requiredCount, const std::set< std::string > &excludeIds, const std::string &modelName, const FoodGenerateParams &params, PresetType preset, std::map< std::string, QualityChecker::QualityResult > &qualityResults)
static int ProcessLLMResponse_Food (const std::string &jsonResponse, const std::string &outputPath, int requiredCount, const std::set< std::string > &excludeIds, const std::string &modelName, const FoodGenerateParams &params, PresetType preset, std::map< std::string, QualityChecker::QualityResult > &qualityResults)
static int ProcessLLMResponse_Material (const std::string &jsonResponse, const std::string &outputPath, int requiredCount, const std::set< std::string > &excludeIds, const std::string &modelName, const FoodGenerateParams &params, PresetType preset, std::map< std::string, QualityChecker::QualityResult > &qualityResults)
static int ProcessLLMResponse_Weapon (const std::string &jsonResponse, const std::string &outputPath, int requiredCount, const std::set< std::string > &excludeIds, const std::string &modelName, const FoodGenerateParams &params, PresetType preset, std::map< std::string, QualityChecker::QualityResult > &qualityResults)
static int ProcessLLMResponse_WeaponComponent (const std::string &jsonResponse, const std::string &outputPath, int requiredCount, const std::set< std::string > &excludeIds, const std::string &modelName, const FoodGenerateParams &params, PresetType preset, std::map< std::string, QualityChecker::QualityResult > &qualityResults)
int ItemGenerator::GenerateWithLLM_SingleBatch (const CommandLineArgs &args, const std::set< std::string > &existingIds, bool useCustomPreset, const CustomPreset &customPreset)
template<typename ItemType, typename ParseFunc, typename QualityCheckFunc, typename WriteFunc, typename GetExistingIdsFunc, typename BuildPromptFunc, typename ProcessRecursiveFunc, typename PostProcessFunc = std::function<void(std::vector<ItemType>&)>>
static int ProcessLLMResponse_Common (const std::string &jsonResponse, const std::string &outputPath, int requiredCount, const std::set< std::string > &excludeIds, const std::string &modelName, const FoodGenerateParams &params, PresetType preset, const std::string &itemTypeName, const std::string &registrySlug, ParseFunc parseFunc, QualityCheckFunc qualityCheckFunc, WriteFunc writeFunc, GetExistingIdsFunc getExistingIdsFunc, BuildPromptFunc buildPromptFunc, ProcessRecursiveFunc processRecursiveFunc, std::map< std::string, QualityChecker::QualityResult > &qualityResults, PostProcessFunc postProcessFunc=[](std::vector< ItemType > &) {})
Common template-based processing logic for LLM responses.
int ItemGenerator::GenerateWithLLM (const CommandLineArgs &args)
Generate items of a single type using LLM.
int ItemGenerator::GenerateBatch (const CommandLineArgs &args)
Generate multiple item types in batch mode.
Function Documentation
AppendIdsToRegistry()
template<typename T> void AppendIdsToRegistry (const std::string & typeName, const std::vector< T > & items) static
Definition at line 163 of file ItemGenerator.cpp.
References LoadRegistryIds(), LogRegistryEvent(), and SaveRegistryIds().
Referenced by ProcessLLMResponse_Ammo(), and ProcessLLMResponse_WeaponComponent().
CleanJsonTrailingCommas()
std::string CleanJsonTrailingCommas (const std::string & text) static
Definition at line 181 of file ItemGenerator.cpp.
Referenced by ProcessLLMResponse_Ammo(), and ProcessLLMResponse_WeaponComponent().
EnsureParentDir()
void EnsureParentDir (const std::string & path) static
Definition at line 91 of file ItemGenerator.cpp.
Referenced by SaveRegistryIds(), and SaveTextFile().
GetCurrentTimestamp()
std::string GetCurrentTimestamp () static
Definition at line 213 of file ItemGenerator.cpp.
Referenced by ItemGenerator::GenerateWithLLM_SingleBatch(), ProcessLLMResponse_Ammo(), and ProcessLLMResponse_WeaponComponent().
GetRegistryPath()
std::string GetRegistryPath (const std::string & typeName) static
Definition at line 108 of file ItemGenerator.cpp.
Referenced by LoadRegistryIds(), and SaveRegistryIds().
LoadRegistryIds()
std::set< std::string > LoadRegistryIds (const std::string & typeName) static
Definition at line 113 of file ItemGenerator.cpp.
References GetRegistryPath().
Referenced by AppendIdsToRegistry(), and ItemGenerator::GenerateWithLLM().
LogRegistryEvent()
void LogRegistryEvent (const std::string & typeName, size_t beforeCount, size_t addedCount, size_t afterCount) static
Definition at line 156 of file ItemGenerator.cpp.
Referenced by AppendIdsToRegistry(), and ItemGenerator::GenerateWithLLM().
ProcessLLMResponse_Ammo()
int ProcessLLMResponse_Ammo (const std::string & jsonResponse, const std::string & outputPath, int requiredCount, const std::set< std::string > & excludeIds, const std::string & modelName, const FoodGenerateParams & params, PresetType preset, std::map< std::string, QualityChecker::QualityResult > & qualityResults) static
Definition at line 1095 of file ItemGenerator.cpp.
References AppendIdsToRegistry(), PromptBuilder::BuildAmmoJsonPrompt(), QualityChecker::CheckAmmoQuality(), CleanJsonTrailingCommas(), FoodGenerateParams::count, GetCurrentTimestamp(), ItemJsonWriter::GetExistingAmmoIds(), ItemJsonParser::ParseAmmoFromJsonText(), QualityChecker::PrintQualityResult(), ProcessLLMResponse_Ammo(), OllamaClient::RunWithRetry(), SaveTextFile(), and ItemJsonWriter::WriteAmmoToFile().
Referenced by ItemGenerator::GenerateWithLLM_SingleBatch(), and ProcessLLMResponse_Ammo().
ProcessLLMResponse_Common()
template<typename ItemType, typename ParseFunc, typename QualityCheckFunc, typename WriteFunc, typename GetExistingIdsFunc, typename BuildPromptFunc, typename ProcessRecursiveFunc, typename PostProcessFunc = std::function<void(std::vector<ItemType>&)>> int ProcessLLMResponse_Common (const std::string & jsonResponse, const std::string & outputPath, int requiredCount, const std::set< std::string > & excludeIds, const std::string & modelName, const FoodGenerateParams & params, PresetType preset, const std::string & itemTypeName, const std::string & registrySlug, ParseFunc parseFunc, QualityCheckFunc qualityCheckFunc, WriteFunc writeFunc, GetExistingIdsFunc getExistingIdsFunc, BuildPromptFunc buildPromptFunc, ProcessRecursiveFunc processRecursiveFunc, std::map< std::string, QualityChecker::QualityResult > & qualityResults, PostProcessFunc postProcessFunc = [](std::vector<ItemType>&) {}) static
Common template-based processing logic for LLM responses.
This template function extracts the common logic from ProcessLLMResponse_* functions. Type-specific operations are passed as function objects/lambdas. All item types now use qualityResults for unified invalid item filtering.
Template Parameters
ItemType The item data type (ItemFoodData, ItemDrinkData, etc.)
ParseFunc Function type: bool(const std::string&, std::vector<ItemType>&)
QualityCheckFunc Function type: QualityChecker::QualityResult(const ItemType&)
WriteFunc Function type: bool(const std::string&, const std::vector<ItemType>&)
GetExistingIdsFunc Function type: std::set<std::string>(const std::string&)
BuildPromptFunc Function type: std::string(...)
ProcessRecursiveFunc Function type: int(...)
PostProcessFunc Function type: void(std::vector<ItemType>&) - optional
Parameters
jsonResponse Raw JSON response from LLM
outputPath Path to output JSON file
requiredCount Target number of items to generate
excludeIds Set of existing item IDs to exclude (duplicates)
modelName LLM model name for recursive calls
params Generation parameters (maxHunger, maxThirst, etc.)
preset Preset type (Default, Forest, Desert, etc.)
itemTypeName Human-readable item type name (for logging)
registrySlug Registry slug for ID tracking
parseFunc Function to parse JSON into items
qualityCheckFunc Function to perform quality checking
writeFunc Function to write items to file
getExistingIdsFunc Function to load existing IDs from file
buildPromptFunc Function to build LLM prompt
processRecursiveFunc Function to recursively generate more items if needed
[in,out] qualityResults Map to store quality check results (used for filtering)
postProcessFunc Optional function to post-process items before validation
Returns
Number of items successfully added, or negative on error
Note
Saves raw JSON response to .raw.json file
Filters out duplicate IDs and invalid items (based on qualityResults)
Automatically merges with existing items in output file
Recursively generates more items if count is insufficient
Definition at line 299 of file ItemGenerator.cpp.
Referenced by ProcessLLMResponse_Drink(), ProcessLLMResponse_Food(), ProcessLLMResponse_Material(), and ProcessLLMResponse_Weapon().
ProcessLLMResponse_Drink()
int ProcessLLMResponse_Drink (const std::string & jsonResponse, const std::string & outputPath, int requiredCount, const std::set< std::string > & excludeIds, const std::string & modelName, const FoodGenerateParams & params, PresetType preset, std::map< std::string, QualityChecker::QualityResult > & qualityResults) static
Definition at line 576 of file ItemGenerator.cpp.
References PromptBuilder::BuildDrinkJsonPrompt(), QualityChecker::CheckDrinkQuality(), ItemJsonWriter::GetExistingDrinkIds(), ItemJsonParser::ParseDrinkFromJsonText(), ProcessLLMResponse_Common(), ProcessLLMResponse_Drink(), and ItemJsonWriter::WriteDrinkToFile().
Referenced by ItemGenerator::GenerateWithLLM_SingleBatch(), and ProcessLLMResponse_Drink().
ProcessLLMResponse_Food()
int ProcessLLMResponse_Food (const std::string & jsonResponse, const std::string & outputPath, int requiredCount, const std::set< std::string > & excludeIds, const std::string & modelName, const FoodGenerateParams & params, PresetType preset, std::map< std::string, QualityChecker::QualityResult > & qualityResults) static
Definition at line 541 of file ItemGenerator.cpp.
References PromptBuilder::BuildFoodJsonPrompt(), QualityChecker::CheckFoodQuality(), ItemJsonWriter::GetExistingFoodIds(), ItemJsonParser::ParseFoodFromJsonText(), ProcessLLMResponse_Common(), ProcessLLMResponse_Food(), and ItemJsonWriter::WriteFoodToFile().
Referenced by ItemGenerator::GenerateWithLLM_SingleBatch(), and ProcessLLMResponse_Food().
ProcessLLMResponse_Material()
int ProcessLLMResponse_Material (const std::string & jsonResponse, const std::string & outputPath, int requiredCount, const std::set< std::string > & excludeIds, const std::string & modelName, const FoodGenerateParams & params, PresetType preset, std::map< std::string, QualityChecker::QualityResult > & qualityResults) static
Definition at line 611 of file ItemGenerator.cpp.
References PromptBuilder::BuildMaterialJsonPrompt(), QualityChecker::CheckMaterialQuality(), ItemJsonWriter::GetExistingMaterialIds(), ItemJsonParser::ParseMaterialFromJsonText(), ProcessLLMResponse_Common(), ProcessLLMResponse_Material(), and ItemJsonWriter::WriteMaterialToFile().
Referenced by ItemGenerator::GenerateWithLLM_SingleBatch(), and ProcessLLMResponse_Material().
ProcessLLMResponse_Weapon()
int ProcessLLMResponse_Weapon (const std::string & jsonResponse, const std::string & outputPath, int requiredCount, const std::set< std::string > & excludeIds, const std::string & modelName, const FoodGenerateParams & params, PresetType preset, std::map< std::string, QualityChecker::QualityResult > & qualityResults) static
Definition at line 642 of file ItemGenerator.cpp.
References PromptBuilder::BuildWeaponJsonPrompt(), QualityChecker::CheckWeaponQuality(), ItemJsonWriter::GetExistingWeaponIds(), ItemJsonParser::ParseWeaponFromJsonText(), ProcessLLMResponse_Common(), ProcessLLMResponse_Weapon(), and ItemJsonWriter::WriteWeaponToFile().
Referenced by ItemGenerator::GenerateWithLLM_SingleBatch(), and ProcessLLMResponse_Weapon().
ProcessLLMResponse_WeaponComponent()
int ProcessLLMResponse_WeaponComponent (const std::string & jsonResponse, const std::string & outputPath, int requiredCount, const std::set< std::string > & excludeIds, const std::string & modelName, const FoodGenerateParams & params, PresetType preset, std::map< std::string, QualityChecker::QualityResult > & qualityResults) static
Definition at line 681 of file ItemGenerator.cpp.
References AppendIdsToRegistry(), PromptBuilder::BuildWeaponComponentJsonPrompt(), QualityChecker::CheckWeaponComponentQuality(), CleanJsonTrailingCommas(), FoodGenerateParams::count, GetCurrentTimestamp(), ItemJsonWriter::GetExistingWeaponComponentIds(), ItemJsonParser::ParseWeaponComponentFromJsonText(), QualityChecker::PrintQualityResult(), ProcessLLMResponse_WeaponComponent(), OllamaClient::RunWithRetry(), SaveTextFile(), and ItemJsonWriter::WriteWeaponComponentToFile().
Referenced by ItemGenerator::GenerateWithLLM_SingleBatch(), and ProcessLLMResponse_WeaponComponent().
SaveRegistryIds()
bool SaveRegistryIds (const std::string & typeName, const std::set< std::string > & ids) static
Definition at line 140 of file ItemGenerator.cpp.
References EnsureParentDir(), and GetRegistryPath().
Referenced by AppendIdsToRegistry().
SaveTextFile()
bool SaveTextFile (const std::string & path, const std::string & text) static
Definition at line 200 of file ItemGenerator.cpp.
References EnsureParentDir().
Referenced by ProcessLLMResponse_Ammo(), and ProcessLLMResponse_WeaponComponent().