RundeeItemFactory: ItemGenerator Class Reference
ItemGenerator Class Reference
High-level item generation using LLM.
#include <ItemGenerator.h>
Static Public Member Functions
static int GenerateWithLLM (CommandLineArgs &args)
Generate items using LLM.
Detailed Description
High-level item generation using LLM.
Definition at line 17 of file ItemGenerator.h.
Member Function Documentation
GenerateWithLLM()
int ItemGenerator::GenerateWithLLM (CommandLineArgs & args) static
Generate items using LLM.
Parameters
args Command line arguments (may be modified to apply player profile settings)
Returns
Exit code (0 = success)
Definition at line 179 of file ItemGenerator.cpp.
References DynamicPromptBuilder::BuildPromptFromProfile(), ItemProfile::displayName, PlayerProfile::displayName, EnsureParentDir(), DynamicItemJsonParser::GenerateShortIdFromDisplayName(), PlayerProfileManager::GetDefaultProfile(), DynamicItemJsonWriter::GetExistingIds(), CommandLineParser::GetItemTypeName(), ItemProfile::id, PlayerProfile::id, ItemProfileManager::Initialize(), CommandLineArgs::itemType, ItemProfile::itemTypeName, ItemProfileManager::LoadProfile(), PlayerProfileManager::LoadProfile(), ItemGeneratorRegistry::LoadRegistryIds(), ItemGeneratorRegistry::LogRegistryEvent(), FoodGenerateParams::maxEnergy, PlayerSettings::maxEnergy, FoodGenerateParams::maxHealth, PlayerSettings::maxHealth, FoodGenerateParams::maxHunger, PlayerSettings::maxHunger, FoodGenerateParams::maxStamina, PlayerSettings::maxStamina, FoodGenerateParams::maxThirst, PlayerSettings::maxThirst, FoodGenerateParams::maxWeight, PlayerSettings::maxWeight, CommandLineArgs::modelName, FoodGenerateParams::outputPath, CommandLineArgs::params, DynamicItemJsonParser::ParseItemsFromJsonText(), CommandLineArgs::playerProfileId, PlayerProfile::playerSettings, CommandLineArgs::profileId, OllamaClient::RunWithRetry(), ItemGeneratorRegistry::SaveRegistryIds(), and DynamicItemJsonWriter::WriteItemsToFile().
Referenced by main().
The documentation for this class was generated from the following files:
RundeeItemFactory/RundeeItemFactory/include/Generators/ItemGenerator.h
RundeeItemFactory/RundeeItemFactory/src/Generators/ItemGenerator.cpp