RundeeItemFactory: OllamaClient Class Reference
OllamaClient Class Reference
Static class for communicating with Ollama LLM server.
#include <OllamaClient.h>
Static Public Member Functions
static std::string RunSimple (const std::string &modelName, const std::string &prompt, const OllamaSettings &settings)
Simple helper function to call Ollama HTTP API.
static std::string RunWithRetry (const std::string &modelName, const std::string &prompt, int maxRetries=3, int timeoutSeconds=120)
Run LLM call with automatic retry logic.
Detailed Description
Static class for communicating with Ollama LLM server.
Provides methods to send prompts to Ollama and receive JSON responses. Uses HTTP API (WinHTTP on Windows) for communication.
Definition at line 24 of file OllamaClient.h.
Member Function Documentation
RunSimple()
std::string OllamaClient::RunSimple (const std::string & modelName, const std::string & prompt, const OllamaSettings & settings) static
Simple helper function to call Ollama HTTP API.
Makes a single HTTP request to Ollama with the given model and prompt. Uses the provided OllamaSettings for connection configuration.
Parameters
modelName Name of the LLM model (e.g., "llama3", "mistral")
prompt Prompt text to send to the LLM
settings Ollama connection settings (host, port, timeouts)
Returns
JSON response as a string, or empty string on error
Note
This function does not retry on failure
Uses WinHTTP on Windows for HTTP communication
See also
RunWithRetry for automatic retry logic
Definition at line 183 of file OllamaClient.cpp.
References OllamaSettings::connectTimeoutMs, OllamaSettings::host, OllamaSettings::port, OllamaSettings::receiveTimeoutMs, OllamaSettings::requestTimeoutSeconds, and OllamaSettings::sendTimeoutMs.
Referenced by RunWithRetry().
RunWithRetry()
std::string OllamaClient::RunWithRetry (const std::string & modelName, const std::string & prompt, int maxRetries = 3, int timeoutSeconds = 120) static
Run LLM call with automatic retry logic.
Attempts to call the LLM with automatic retry on failure. Uses settings from AppConfig (loaded from config/rundee_config.json).
Parameters
modelName Name of the LLM model (e.g., "llama3", "mistral")
prompt Prompt text to send to the LLM
maxRetries Maximum number of retry attempts (default: 3)
timeoutSeconds Timeout per attempt in seconds (default: 120, 0 = no timeout)
Returns
Response string, or empty string if all attempts failed
Note
Automatically loads OllamaSettings from AppConfig
Retries with exponential backoff on failure
Logs retry attempts to std::cerr
See also
RunSimple for single-call version
Definition at line 405 of file OllamaClient.cpp.
References AppConfig::GetOllamaSettings(), OllamaSettings::maxRetries, OllamaSettings::requestTimeoutSeconds, and RunSimple().
Referenced by ItemGenerator::GenerateWithLLM_SingleBatch(), ProcessLLMResponse_Ammo(), and ProcessLLMResponse_WeaponComponent().
The documentation for this class was generated from the following files:
RundeeItemFactory/RundeeItemFactory/include/Clients/OllamaClient.h
RundeeItemFactory/RundeeItemFactory/src/Clients/OllamaClient.cpp