RundeeItemFactory: ItemJsonParser Class Reference
ItemJsonParser Class Reference
Static parser class for converting JSON text to item data structures.
#include <ItemJsonParser.h>
Static Public Member Functions
static bool ParseFoodFromJsonText (const std::string &jsonText, std::vector< ItemFoodData > &outItems)
Parse food items from JSON text.
static bool ParseDrinkFromJsonText (const std::string &jsonText, std::vector< ItemDrinkData > &outItems)
Parse drink items from JSON text.
static bool ParseMaterialFromJsonText (const std::string &jsonText, std::vector< ItemMaterialData > &outItems)
Parse material items from JSON text.
static bool ParseWeaponFromJsonText (const std::string &jsonText, std::vector< ItemWeaponData > &outItems)
Parse weapon items from JSON text.
static bool ParseWeaponComponentFromJsonText (const std::string &jsonText, std::vector< ItemWeaponComponentData > &outItems)
Parse weapon component items from JSON text.
static bool ParseAmmoFromJsonText (const std::string &jsonText, std::vector< ItemAmmoData > &outItems)
Parse ammo items from JSON text.
Detailed Description
Static parser class for converting JSON text to item data structures.
Provides type-specific parsing methods for each item type. All methods follow the same pattern: take JSON text as input, parse into vector of item data, and return success/failure status.
Definition at line 32 of file ItemJsonParser.h.
Member Function Documentation
ParseAmmoFromJsonText()
bool ItemJsonParser::ParseAmmoFromJsonText (const std::string & jsonText, std::vector< ItemAmmoData > & outItems) static
Parse ammo items from JSON text.
Parameters
jsonText JSON text string containing an array of ammo items
[out] outItems Vector to store parsed ammo items
Returns
true if parsing succeeded, false otherwise
Definition at line 566 of file ItemJsonParser.cpp.
References ItemAmmoData::accuracyBonus, ItemAmmoData::armorPiercing, ItemAmmoData::caliber, ItemDataBase::category, StringUtils::CleanJsonArrayText(), ItemAmmoData::damageBonus, ItemDataBase::description, ItemDataBase::displayName, JsonUtils::GetBoolSafe(), JsonUtils::GetIntSafe(), JsonUtils::GetStringSafe(), ItemAmmoData::hollowPoint, ItemDataBase::id, ItemAmmoData::incendiary, ItemDataBase::maxStack, ItemAmmoData::penetration, ItemDataBase::rarity, ItemAmmoData::recoilModifier, ItemAmmoData::tracer, AmmoItemValidator::Validate(), and ItemAmmoData::value.
Referenced by BalanceReporter::GenerateReport(), ItemJsonWriter::GetExistingAmmoIds(), ItemJsonWriter::MergeAmmoToFile(), and ProcessLLMResponse_Ammo().
ParseDrinkFromJsonText()
bool ItemJsonParser::ParseDrinkFromJsonText (const std::string & jsonText, std::vector< ItemDrinkData > & outItems) static
Parse drink items from JSON text.
Parameters
jsonText JSON text string containing an array of drink items
[out] outItems Vector to store parsed drink items
Returns
true if parsing succeeded, false otherwise
Definition at line 150 of file ItemJsonParser.cpp.
References ItemDataBase::category, StringUtils::CleanJsonArrayText(), ItemDataBase::description, ItemDataBase::displayName, JsonUtils::GetBoolSafe(), JsonUtils::GetIntSafe(), JsonUtils::GetStringSafe(), ItemDrinkData::healthRestore, ItemDrinkData::hungerRestore, ItemDataBase::id, ItemDataBase::maxStack, ItemDataBase::rarity, ItemDrinkData::spoils, ItemDrinkData::spoilTimeMinutes, ItemDrinkData::thirstRestore, and DrinkItemValidator::Validate().
Referenced by BalanceReporter::GenerateReport(), ItemJsonWriter::GetExistingDrinkIds(), ItemJsonWriter::MergeDrinkToFile(), and ProcessLLMResponse_Drink().
ParseFoodFromJsonText()
bool ItemJsonParser::ParseFoodFromJsonText (const std::string & jsonText, std::vector< ItemFoodData > & outItems) static
Parse food items from JSON text.
Parses a JSON array of food items from the provided JSON text string. Handles JSON cleaning, validation, and error reporting.
Parameters
jsonText JSON text string containing an array of food items
[out] outItems Vector to store parsed food items
Returns
true if parsing succeeded, false otherwise
Note
The JSON text is automatically cleaned (trailing commas, whitespace)
Items with missing required fields (id, displayName) are skipped
Only items with category "Food" are parsed
Definition at line 38 of file ItemJsonParser.cpp.
References ItemDataBase::category, StringUtils::CleanJsonArrayText(), ItemDataBase::description, ItemDataBase::displayName, JsonUtils::GetBoolSafe(), JsonUtils::GetIntSafe(), JsonUtils::GetStringSafe(), ItemFoodData::healthRestore, ItemFoodData::hungerRestore, ItemDataBase::id, ItemDataBase::maxStack, ItemDataBase::rarity, ItemFoodData::spoils, ItemFoodData::spoilTimeMinutes, ItemFoodData::thirstRestore, and FoodItemValidator::Validate().
Referenced by BalanceReporter::GenerateReport(), ItemJsonWriter::GetExistingFoodIds(), ItemJsonWriter::MergeFoodToFile(), and ProcessLLMResponse_Food().
ParseMaterialFromJsonText()
bool ItemJsonParser::ParseMaterialFromJsonText (const std::string & jsonText, std::vector< ItemMaterialData > & outItems) static
Parse material items from JSON text.
Parameters
jsonText JSON text string containing an array of material items
[out] outItems Vector to store parsed material items
Returns
true if parsing succeeded, false otherwise
Definition at line 228 of file ItemJsonParser.cpp.
References ItemDataBase::category, StringUtils::CleanJsonArrayText(), ItemDataBase::description, ItemDataBase::displayName, ItemMaterialData::flammability, JsonUtils::GetIntSafe(), JsonUtils::GetStringSafe(), ItemMaterialData::hardness, ItemDataBase::id, ItemMaterialData::materialType, ItemDataBase::maxStack, ItemDataBase::rarity, MaterialItemValidator::Validate(), and ItemMaterialData::value.
Referenced by BalanceReporter::GenerateReport(), ItemJsonWriter::GetExistingMaterialIds(), ItemJsonWriter::MergeMaterialToFile(), and ProcessLLMResponse_Material().
ParseWeaponComponentFromJsonText()
bool ItemJsonParser::ParseWeaponComponentFromJsonText (const std::string & jsonText, std::vector< ItemWeaponComponentData > & outItems) static
Parse weapon component items from JSON text.
Parameters
jsonText JSON text string containing an array of weapon component items
[out] outItems Vector to store parsed weapon component items
Returns
true if parsing succeeded, false otherwise
Definition at line 433 of file ItemJsonParser.cpp.
References ItemWeaponComponentData::accuracyModifier, LoadedRoundSegment::ammoDisplayName, LoadedRoundSegment::ammoId, LoadedRoundSegment::ammoNotes, ItemWeaponComponentData::caliber, ItemDataBase::category, StringUtils::CleanJsonArrayText(), ItemWeaponComponentData::compatibleSlots, ItemWeaponComponentData::componentType, ItemWeaponComponentData::damageModifier, ItemDataBase::description, ItemDataBase::displayName, ItemWeaponComponentData::effectiveRangeModifier, ItemWeaponComponentData::ergonomicsModifier, JsonUtils::GetBoolSafe(), JsonUtils::GetIntSafe(), JsonUtils::GetStringSafe(), ComponentAttachmentSlot::hasBuiltInRail, ItemWeaponComponentData::hasBuiltInRail, ItemDataBase::id, ItemWeaponComponentData::loadedRounds, ItemWeaponComponentData::magazineCapacity, ItemWeaponComponentData::magazineType, ItemDataBase::maxStack, ItemWeaponComponentData::muzzleVelocityModifier, LoadedRoundSegment::orderIndex, ItemWeaponComponentData::penetrationModifier, ItemWeaponComponentData::railType, ItemDataBase::rarity, ItemWeaponComponentData::recoilModifier, LoadedRoundSegment::roundCount, ComponentAttachmentSlot::slotIndex, ComponentAttachmentSlot::slotType, ItemWeaponComponentData::subSlots, WeaponComponentItemValidator::Validate(), and ItemWeaponComponentData::weightModifier.
Referenced by BalanceReporter::GenerateReport(), ItemJsonWriter::GetExistingWeaponComponentIds(), ItemJsonWriter::MergeWeaponComponentToFile(), and ProcessLLMResponse_WeaponComponent().
ParseWeaponFromJsonText()
bool ItemJsonParser::ParseWeaponFromJsonText (const std::string & jsonText, std::vector< ItemWeaponData > & outItems) static
Parse weapon items from JSON text.
Parameters
jsonText JSON text string containing an array of weapon items
[out] outItems Vector to store parsed weapon items
Returns
true if parsing succeeded, false otherwise
Definition at line 292 of file ItemJsonParser.cpp.
References ItemWeaponData::accuracy, ItemWeaponData::attachmentSlots, ItemWeaponData::attackSpeed, ItemWeaponData::caliber, ItemDataBase::category, StringUtils::CleanJsonArrayText(), ItemDataBase::description, ItemDataBase::displayName, ItemWeaponData::durability, ItemWeaponData::effectiveRange, ItemWeaponData::ergonomics, ItemWeaponData::fireRate, JsonUtils::GetBoolSafe(), JsonUtils::GetIntSafe(), JsonUtils::GetStringSafe(), ItemDataBase::id, WeaponAttachmentSlot::isRequired, ItemWeaponData::maxDamage, ItemDataBase::maxStack, ItemWeaponData::minDamage, ItemWeaponData::moddingSlots, ItemWeaponData::muzzleVelocity, ItemWeaponData::penetrationPower, ItemDataBase::rarity, ItemWeaponData::reach, ItemWeaponData::recoil, WeaponAttachmentSlot::slotIndex, WeaponAttachmentSlot::slotType, ItemWeaponData::staminaCost, WeaponItemValidator::Validate(), ItemWeaponData::weaponCategory, ItemWeaponData::weaponType, and ItemWeaponData::weight.
Referenced by BalanceReporter::GenerateReport(), ItemJsonWriter::GetExistingWeaponIds(), ItemJsonWriter::MergeWeaponToFile(), and ProcessLLMResponse_Weapon().
The documentation for this class was generated from the following files:
RundeeItemFactory/RundeeItemFactory/include/Parsers/ItemJsonParser.h
RundeeItemFactory/RundeeItemFactory/src/Parsers/ItemJsonParser.cpp