RundeeItemFactory: PromptBuilder Class Reference
PromptBuilder Class Reference
Static class for building LLM prompts.
#include <PromptBuilder.h>
Static Public Member Functions
static std::string GetPresetFlavorText (PresetType preset)
Get preset flavor text for built-in preset.
static std::string GetPresetFlavorText (const CustomPreset &customPreset)
Get preset flavor text for custom preset.
static std::string BuildFoodJsonPrompt (const FoodGenerateParams &params, PresetType preset, const std::set< std::string > &excludeIds=std::set< std::string >(), const std::string &modelName=std::string(), const std::string &generationTimestamp=std::string(), int existingCount=-1)
Build food item generation prompt (built-in preset).
static std::string BuildFoodJsonPrompt (const FoodGenerateParams &params, const CustomPreset &customPreset, const std::set< std::string > &excludeIds=std::set< std::string >(), const std::string &modelName=std::string(), const std::string &generationTimestamp=std::string(), int existingCount=-1)
Build food item generation prompt (custom preset).
static std::string BuildDrinkJsonPrompt (const FoodGenerateParams &params, PresetType preset, const std::set< std::string > &excludeIds=std::set< std::string >(), const std::string &modelName=std::string(), const std::string &generationTimestamp=std::string(), int existingCount=-1)
Build drink item generation prompt (built-in preset).
static std::string BuildDrinkJsonPrompt (const FoodGenerateParams &params, const CustomPreset &customPreset, const std::set< std::string > &excludeIds=std::set< std::string >(), const std::string &modelName=std::string(), const std::string &generationTimestamp=std::string(), int existingCount=-1)
Build drink item generation prompt (custom preset).
static std::string BuildMaterialJsonPrompt (const FoodGenerateParams &params, PresetType preset, const std::set< std::string > &excludeIds=std::set< std::string >(), const std::string &modelName=std::string(), const std::string &generationTimestamp=std::string(), int existingCount=-1)
Build material item generation prompt (built-in preset).
static std::string BuildMaterialJsonPrompt (const FoodGenerateParams &params, const CustomPreset &customPreset, const std::set< std::string > &excludeIds=std::set< std::string >(), const std::string &modelName=std::string(), const std::string &generationTimestamp=std::string(), int existingCount=-1)
Build material item generation prompt (custom preset).
static std::string BuildWeaponJsonPrompt (const FoodGenerateParams &params, PresetType preset, const std::set< std::string > &excludeIds=std::set< std::string >(), const std::string &modelName=std::string(), const std::string &generationTimestamp=std::string(), int existingCount=-1)
Build weapon item generation prompt (built-in preset).
static std::string BuildWeaponJsonPrompt (const FoodGenerateParams &params, const CustomPreset &customPreset, const std::set< std::string > &excludeIds=std::set< std::string >(), const std::string &modelName=std::string(), const std::string &generationTimestamp=std::string(), int existingCount=-1)
Build weapon item generation prompt (custom preset).
static std::string BuildWeaponComponentJsonPrompt (const FoodGenerateParams &params, PresetType preset, const std::set< std::string > &excludeIds=std::set< std::string >(), const std::string &modelName=std::string(), const std::string &generationTimestamp=std::string(), int existingCount=-1)
Build weapon component item generation prompt (built-in preset).
static std::string BuildWeaponComponentJsonPrompt (const FoodGenerateParams &params, const CustomPreset &customPreset, const std::set< std::string > &excludeIds=std::set< std::string >(), const std::string &modelName=std::string(), const std::string &generationTimestamp=std::string(), int existingCount=-1)
Build weapon component item generation prompt (custom preset).
static std::string BuildAmmoJsonPrompt (const FoodGenerateParams &params, PresetType preset, const std::set< std::string > &excludeIds=std::set< std::string >(), const std::string &modelName=std::string(), const std::string &generationTimestamp=std::string(), int existingCount=-1)
Build ammo item generation prompt (built-in preset).
static std::string BuildAmmoJsonPrompt (const FoodGenerateParams &params, const CustomPreset &customPreset, const std::set< std::string > &excludeIds=std::set< std::string >(), const std::string &modelName=std::string(), const std::string &generationTimestamp=std::string(), int existingCount=-1)
Build ammo item generation prompt (custom preset).
Detailed Description
Static class for building LLM prompts.
Constructs detailed prompts for LLM item generation, including context, constraints, examples, and formatting instructions. Supports all item types and both built-in and custom presets.
Definition at line 44 of file PromptBuilder.h.
Member Function Documentation
BuildAmmoJsonPrompt() [1/2]
std::string PromptBuilder::BuildAmmoJsonPrompt (const FoodGenerateParams & params, const CustomPreset & customPreset, const std::set< std::string > & excludeIds = std::set<std::string>(), const std::string & modelName = std::string(), const std::string & generationTimestamp = std::string(), int existingCount = -1) static
Build ammo item generation prompt (custom preset).
Parameters
params Generation parameters
customPreset Custom preset structure
excludeIds Set of existing item IDs
modelName LLM model name
generationTimestamp Timestamp of generation
existingCount Number of existing items
Returns
Complete prompt string for LLM
Definition at line 1273 of file PromptBuilder.cpp.
References FoodGenerateParams::count, CustomPreset::displayName, GetPresetFlavorText(), and CustomPreset::id.
BuildAmmoJsonPrompt() [2/2]
std::string PromptBuilder::BuildAmmoJsonPrompt (const FoodGenerateParams & params, PresetType preset, const std::set< std::string > & excludeIds = std::set<std::string>(), const std::string & modelName = std::string(), const std::string & generationTimestamp = std::string(), int existingCount = -1) static
Build ammo item generation prompt (built-in preset).
Parameters
params Generation parameters
preset Built-in preset type
excludeIds Set of existing item IDs
modelName LLM model name
generationTimestamp Timestamp of generation
existingCount Number of existing items
Returns
Complete prompt string for LLM
Definition at line 1175 of file PromptBuilder.cpp.
References FoodGenerateParams::count, and GetPresetFlavorText().
Referenced by ItemGenerator::GenerateWithLLM_SingleBatch(), and ProcessLLMResponse_Ammo().
BuildDrinkJsonPrompt() [1/2]
std::string PromptBuilder::BuildDrinkJsonPrompt (const FoodGenerateParams & params, const CustomPreset & customPreset, const std::set< std::string > & excludeIds = std::set<std::string>(), const std::string & modelName = std::string(), const std::string & generationTimestamp = std::string(), int existingCount = -1) static
Build drink item generation prompt (custom preset).
Parameters
params Generation parameters
customPreset Custom preset structure
excludeIds Set of existing item IDs
modelName LLM model name
generationTimestamp Timestamp of generation
existingCount Number of existing items
Returns
Complete prompt string for LLM
Definition at line 451 of file PromptBuilder.cpp.
References FoodGenerateParams::count, CustomPreset::displayName, GetPresetFlavorText(), CustomPreset::id, FoodGenerateParams::maxHunger, and FoodGenerateParams::maxThirst.
BuildDrinkJsonPrompt() [2/2]
std::string PromptBuilder::BuildDrinkJsonPrompt (const FoodGenerateParams & params, PresetType preset, const std::set< std::string > & excludeIds = std::set<std::string>(), const std::string & modelName = std::string(), const std::string & generationTimestamp = std::string(), int existingCount = -1) static
Build drink item generation prompt (built-in preset).
Parameters
params Generation parameters
preset Built-in preset type
excludeIds Set of existing item IDs
modelName LLM model name
generationTimestamp Timestamp of generation
existingCount Number of existing items
Returns
Complete prompt string for LLM
Definition at line 360 of file PromptBuilder.cpp.
References FoodGenerateParams::count, GetPresetFlavorText(), FoodGenerateParams::maxHunger, and FoodGenerateParams::maxThirst.
Referenced by ItemGenerator::GenerateWithLLM_SingleBatch(), and ProcessLLMResponse_Drink().
BuildFoodJsonPrompt() [1/2]
std::string PromptBuilder::BuildFoodJsonPrompt (const FoodGenerateParams & params, const CustomPreset & customPreset, const std::set< std::string > & excludeIds = std::set<std::string>(), const std::string & modelName = std::string(), const std::string & generationTimestamp = std::string(), int existingCount = -1) static
Build food item generation prompt (custom preset).
Parameters
params Generation parameters
customPreset Custom preset structure
excludeIds Set of existing item IDs
modelName LLM model name
generationTimestamp Timestamp of generation
existingCount Number of existing items
Returns
Complete prompt string for LLM
Definition at line 271 of file PromptBuilder.cpp.
References FoodGenerateParams::count, CustomPreset::displayName, GetPresetFlavorText(), CustomPreset::id, FoodGenerateParams::maxHunger, and FoodGenerateParams::maxThirst.
BuildFoodJsonPrompt() [2/2]
std::string PromptBuilder::BuildFoodJsonPrompt (const FoodGenerateParams & params, PresetType preset, const std::set< std::string > & excludeIds = std::set<std::string>(), const std::string & modelName = std::string(), const std::string & generationTimestamp = std::string(), int existingCount = -1) static
Build food item generation prompt (built-in preset).
Constructs a complete prompt for generating food items using a built-in preset. Includes context, constraints, examples, and JSON format instructions.
Parameters
params Generation parameters (count, maxHunger, maxThirst, etc.)
preset Built-in preset type
excludeIds Set of existing item IDs to avoid duplicates
modelName LLM model name (for context)
generationTimestamp Timestamp of generation (for logging)
existingCount Number of existing items (for context)
Returns
Complete prompt string for LLM
Definition at line 177 of file PromptBuilder.cpp.
References FoodGenerateParams::count, GetPresetFlavorText(), FoodGenerateParams::maxHunger, and FoodGenerateParams::maxThirst.
Referenced by ItemGenerator::GenerateWithLLM_SingleBatch(), and ProcessLLMResponse_Food().
BuildMaterialJsonPrompt() [1/2]
std::string PromptBuilder::BuildMaterialJsonPrompt (const FoodGenerateParams & params, const CustomPreset & customPreset, const std::set< std::string > & excludeIds = std::set<std::string>(), const std::string & modelName = std::string(), const std::string & generationTimestamp = std::string(), int existingCount = -1) static
Build material item generation prompt (custom preset).
Parameters
params Generation parameters
customPreset Custom preset structure
excludeIds Set of existing item IDs
modelName LLM model name
generationTimestamp Timestamp of generation
existingCount Number of existing items
Returns
Complete prompt string for LLM
Definition at line 610 of file PromptBuilder.cpp.
References FoodGenerateParams::count, CustomPreset::displayName, GetPresetFlavorText(), and CustomPreset::id.
BuildMaterialJsonPrompt() [2/2]
std::string PromptBuilder::BuildMaterialJsonPrompt (const FoodGenerateParams & params, PresetType preset, const std::set< std::string > & excludeIds = std::set<std::string>(), const std::string & modelName = std::string(), const std::string & generationTimestamp = std::string(), int existingCount = -1) static
Build material item generation prompt (built-in preset).
Parameters
params Generation parameters
preset Built-in preset type
excludeIds Set of existing item IDs
modelName LLM model name
generationTimestamp Timestamp of generation
existingCount Number of existing items
Returns
Complete prompt string for LLM
Definition at line 528 of file PromptBuilder.cpp.
References FoodGenerateParams::count, and GetPresetFlavorText().
Referenced by ItemGenerator::GenerateWithLLM_SingleBatch(), and ProcessLLMResponse_Material().
BuildWeaponComponentJsonPrompt() [1/2]
std::string PromptBuilder::BuildWeaponComponentJsonPrompt (const FoodGenerateParams & params, const CustomPreset & customPreset, const std::set< std::string > & excludeIds = std::set<std::string>(), const std::string & modelName = std::string(), const std::string & generationTimestamp = std::string(), int existingCount = -1) static
Build weapon component item generation prompt (custom preset).
Parameters
params Generation parameters
customPreset Custom preset structure
excludeIds Set of existing item IDs
modelName LLM model name
generationTimestamp Timestamp of generation
existingCount Number of existing items
Returns
Complete prompt string for LLM
Definition at line 1086 of file PromptBuilder.cpp.
References FoodGenerateParams::count, CustomPreset::displayName, GetPresetFlavorText(), and CustomPreset::id.
BuildWeaponComponentJsonPrompt() [2/2]
std::string PromptBuilder::BuildWeaponComponentJsonPrompt (const FoodGenerateParams & params, PresetType preset, const std::set< std::string > & excludeIds = std::set<std::string>(), const std::string & modelName = std::string(), const std::string & generationTimestamp = std::string(), int existingCount = -1) static
Build weapon component item generation prompt (built-in preset).
Parameters
params Generation parameters
preset Built-in preset type
excludeIds Set of existing item IDs
modelName LLM model name
generationTimestamp Timestamp of generation
existingCount Number of existing items
Returns
Complete prompt string for LLM
Definition at line 927 of file PromptBuilder.cpp.
References FoodGenerateParams::count, and GetPresetFlavorText().
Referenced by ItemGenerator::GenerateWithLLM_SingleBatch(), and ProcessLLMResponse_WeaponComponent().
BuildWeaponJsonPrompt() [1/2]
std::string PromptBuilder::BuildWeaponJsonPrompt (const FoodGenerateParams & params, const CustomPreset & customPreset, const std::set< std::string > & excludeIds = std::set<std::string>(), const std::string & modelName = std::string(), const std::string & generationTimestamp = std::string(), int existingCount = -1) static
Build weapon item generation prompt (custom preset).
Parameters
params Generation parameters
customPreset Custom preset structure
excludeIds Set of existing item IDs
modelName LLM model name
generationTimestamp Timestamp of generation
existingCount Number of existing items
Returns
Complete prompt string for LLM
Definition at line 836 of file PromptBuilder.cpp.
References FoodGenerateParams::count, CustomPreset::displayName, GetPresetFlavorText(), and CustomPreset::id.
BuildWeaponJsonPrompt() [2/2]
std::string PromptBuilder::BuildWeaponJsonPrompt (const FoodGenerateParams & params, PresetType preset, const std::set< std::string > & excludeIds = std::set<std::string>(), const std::string & modelName = std::string(), const std::string & generationTimestamp = std::string(), int existingCount = -1) static
Build weapon item generation prompt (built-in preset).
Parameters
params Generation parameters
preset Built-in preset type
excludeIds Set of existing item IDs
modelName LLM model name
generationTimestamp Timestamp of generation
existingCount Number of existing items
Returns
Complete prompt string for LLM
Definition at line 686 of file PromptBuilder.cpp.
References FoodGenerateParams::count, and GetPresetFlavorText().
Referenced by ItemGenerator::GenerateWithLLM_SingleBatch(), and ProcessLLMResponse_Weapon().
GetPresetFlavorText() [1/2]
std::string PromptBuilder::GetPresetFlavorText (const CustomPreset & customPreset) static
Get preset flavor text for custom preset.
Returns world context text from a custom preset.
Parameters
customPreset Custom preset structure
Returns
Flavor text from the custom preset
Definition at line 172 of file PromptBuilder.cpp.
References CustomPresetManager::GetPresetFlavorText().
GetPresetFlavorText() [2/2]
std::string PromptBuilder::GetPresetFlavorText (PresetType preset) static
Get preset flavor text for built-in preset.
Returns world context text for the specified preset type. This text is included in prompts to guide LLM generation.
Parameters
preset Built-in preset type
Returns
Flavor text describing the world context
Definition at line 128 of file PromptBuilder.cpp.
References City, Coast, Default, Desert, and Forest.
Referenced by BuildAmmoJsonPrompt(), BuildAmmoJsonPrompt(), BuildDrinkJsonPrompt(), BuildDrinkJsonPrompt(), BuildFoodJsonPrompt(), BuildFoodJsonPrompt(), BuildMaterialJsonPrompt(), BuildMaterialJsonPrompt(), BuildWeaponComponentJsonPrompt(), BuildWeaponComponentJsonPrompt(), BuildWeaponJsonPrompt(), and BuildWeaponJsonPrompt().
The documentation for this class was generated from the following files:
RundeeItemFactory/RundeeItemFactory/include/Prompts/PromptBuilder.h
RundeeItemFactory/RundeeItemFactory/src/Prompts/PromptBuilder.cpp