RundeeItemFactory: DynamicItemJsonParser Class Reference
DynamicItemJsonParser Class Reference
Static class for parsing items dynamically from JSON.
#include <DynamicItemJsonParser.h>
Static Public Member Functions
static bool ParseItemsFromJsonText (const std::string &jsonText, const ItemProfile &profile, std::vector< nlohmann::json > &outItems)
Parse items from JSON text using a profile.
static bool ValidateItem (const nlohmann::json &item, const ItemProfile &profile, std::vector< std::string > &errors)
Validate an item against its profile.
static void ApplyDefaults (nlohmann::json &item, const ItemProfile &profile)
Apply default values from profile to an item.
static nlohmann::json GetFieldValue (const nlohmann::json &item, const std::string &fieldName, const ItemProfile &profile)
Get field value from item JSON.
static std::string GenerateShortIdFromDisplayName (const std::string &displayName)
Generate short ID from displayName by extracting key identifiers.
Detailed Description
Static class for parsing items dynamically from JSON.
Parses items from JSON text using item profiles to determine the expected structure. Returns items as JSON objects rather than typed structs.
Definition at line 27 of file DynamicItemJsonParser.h.
Member Function Documentation
ApplyDefaults()
void DynamicItemJsonParser::ApplyDefaults (nlohmann::json & item, const ItemProfile & profile) static
Apply default values from profile to an item.
Parameters
item JSON object to modify
profile Profile with default values
Definition at line 159 of file DynamicItemJsonParser.cpp.
References ItemProfile::fields.
Referenced by ParseItemsFromJsonText().
GenerateShortIdFromDisplayName()
std::string DynamicItemJsonParser::GenerateShortIdFromDisplayName (const std::string & displayName) static
Generate short ID from displayName by extracting key identifiers.
Parameters
displayName Display name to process
Returns
Short ID suffix (without prefix)
Definition at line 404 of file DynamicItemJsonParser.cpp.
Referenced by ItemGenerator::GenerateWithLLM().
GetFieldValue()
nlohmann::json DynamicItemJsonParser::GetFieldValue (const nlohmann::json & item, const std::string & fieldName, const ItemProfile & profile) static
Get field value from item JSON.
Parameters
item JSON object
fieldName Field name
profile Profile for type information
Returns
JSON value (can be null if not found)
Definition at line 173 of file DynamicItemJsonParser.cpp.
ParseItemsFromJsonText()
bool DynamicItemJsonParser::ParseItemsFromJsonText (const std::string & jsonText, const ItemProfile & profile, std::vector< nlohmann::json > & outItems) static
Parse items from JSON text using a profile.
Parameters
jsonText JSON text to parse
profile Profile defining the expected structure
outItems Output vector of parsed items (as JSON objects)
Returns
True if parsing succeeded
Definition at line 22 of file DynamicItemJsonParser.cpp.
References ApplyDefaults(), StringUtils::CleanJsonArrayText(), ItemProfile::id, and ValidateItem().
Referenced by ItemGenerator::GenerateWithLLM().
ValidateItem()
bool DynamicItemJsonParser::ValidateItem (const nlohmann::json & item, const ItemProfile & profile, std::vector< std::string > & errors) static
Validate an item against its profile.
Parameters
item JSON object representing an item
profile Profile to validate against
errors Output vector of error messages
Returns
True if item is valid
Definition at line 112 of file DynamicItemJsonParser.cpp.
References ItemProfile::fields.
Referenced by ParseItemsFromJsonText().
The documentation for this class was generated from the following files:
RundeeItemFactory/RundeeItemFactory/include/Parsers/DynamicItemJsonParser.h
RundeeItemFactory/RundeeItemFactory/src/Parsers/DynamicItemJsonParser.cpp