RundeeItemFactory: DynamicItemJsonWriter Class Reference
DynamicItemJsonWriter Class Reference
Static class for writing dynamic item JSON to files.
#include <DynamicItemJsonWriter.h>
Static Public Member Functions
static bool WriteItemsToFile (const std::vector< nlohmann::json > &items, const std::string &path, bool mergeWithExisting=true)
Write dynamic items (JSON objects) to JSON file.
static std::set< std::string > GetExistingIds (const std::string &path)
Get existing item IDs from JSON file.
static bool MergeItemsWithFile (const std::vector< nlohmann::json > &newItems, const std::string &path)
Merge items with existing file, skipping duplicates.
Detailed Description
Static class for writing dynamic item JSON to files.
Definition at line 22 of file DynamicItemJsonWriter.h.
Member Function Documentation
GetExistingIds()
std::set< std::string > DynamicItemJsonWriter::GetExistingIds (const std::string & path) static
Get existing item IDs from JSON file.
Parameters
path JSON file path
Returns
Set of existing item IDs
Definition at line 121 of file DynamicItemJsonWriter.cpp.
Referenced by ItemGenerator::GenerateWithLLM().
MergeItemsWithFile()
bool DynamicItemJsonWriter::MergeItemsWithFile (const std::vector< nlohmann::json > & newItems, const std::string & path) static
Merge items with existing file, skipping duplicates.
Parameters
newItems New items to add
path File path
Returns
true on success, false on failure
Definition at line 161 of file DynamicItemJsonWriter.cpp.
References WriteItemsToFile().
WriteItemsToFile()
bool DynamicItemJsonWriter::WriteItemsToFile (const std::vector< nlohmann::json > & items, const std::string & path, bool mergeWithExisting = true) static
Write dynamic items (JSON objects) to JSON file.
Parameters
items Vector of JSON objects representing items
path Output file path
mergeWithExisting If true, merge with existing items in file (skip duplicates)
Returns
true on success, false on failure
Definition at line 17 of file DynamicItemJsonWriter.cpp.
Referenced by ItemGenerator::GenerateWithLLM(), and MergeItemsWithFile().
The documentation for this class was generated from the following files:
RundeeItemFactory/RundeeItemFactory/include/Writers/DynamicItemJsonWriter.h
RundeeItemFactory/RundeeItemFactory/src/Writers/DynamicItemJsonWriter.cpp