RundeeItemFactory: ItemProfileManager Class Reference
ItemProfileManager Class Reference
Static manager class for item profiles.
#include <ItemProfileManager.h>
Static Public Member Functions
static bool Initialize (const std::string &profilesDir)
Initialize the profile manager.
static ItemProfile LoadProfile (const std::string &profileId)
Load a profile from file.
static ItemProfile LoadProfileFromPath (const std::string &filePath)
Load a profile from file path.
static bool SaveProfile (const ItemProfile &profile)
Save a profile to file.
static ItemProfile GetDefaultProfile (const std::string &itemTypeName)
Get default profile for an item type.
static std::vector< ItemProfile > GetProfilesForType (const std::string &itemTypeName)
Get all profiles for an item type.
static std::map< std::string, ItemProfile > GetAllProfiles ()
Get all available profiles.
static bool ProfileExists (const std::string &profileId)
Check if a profile exists.
static bool DeleteProfile (const std::string &profileId)
Delete a profile.
static bool ValidateProfile (const ItemProfile &profile, std::vector< std::string > &errors)
Validate a profile structure.
static std::string GetProfilesDirectory ()
Get profiles directory.
static bool CreateDefaultProfiles (const std::string &profilesDir)
Create default profiles for built-in item types.
Detailed Description
Static manager class for item profiles.
Handles loading, saving, validation, and lookup of item profiles. Profiles are stored as JSON files in a profiles directory.
Definition at line 26 of file ItemProfileManager.h.
Member Function Documentation
CreateDefaultProfiles()
bool ItemProfileManager::CreateDefaultProfiles (const std::string & profilesDir) static
Create default profiles for built-in item types.
Parameters
profilesDir Directory to create profiles in
Returns
True if creation succeeded
Definition at line 204 of file ItemProfileManager.cpp.
References ProfileFieldValidation::allowedValues, Boolean, ProfileField::category, ProfileField::defaultValue, ItemProfile::description, ProfileField::description, RelationshipConstraint::description, ItemProfile::displayName, ProfileField::displayName, ProfileField::displayOrder, ItemProfile::fields, ItemProfile::id, Integer, ItemProfile::isDefault, ProfileFieldValidation::isRequired, ItemProfile::itemTypeName, ProfileFieldValidation::maxValue, ProfileFieldValidation::minValue, ProfileField::name, RelationshipConstraint::operator_, ProfileFieldValidation::relationshipConstraints, SaveProfile(), String, RelationshipConstraint::targetField, ProfileField::type, ProfileField::validation, and ItemProfile::version.
DeleteProfile()
bool ItemProfileManager::DeleteProfile (const std::string & profileId) static
Delete a profile.
Parameters
profileId Profile ID
Returns
True if deletion succeeded
Definition at line 156 of file ItemProfileManager.cpp.
GetAllProfiles()
std::map< std::string, ItemProfile > ItemProfileManager::GetAllProfiles () static
Get all available profiles.
Returns
Map of profile ID to profile
Definition at line 125 of file ItemProfileManager.cpp.
References ItemProfile::id, and LoadProfileFromPath().
Referenced by GetProfilesForType().
GetDefaultProfile()
ItemProfile ItemProfileManager::GetDefaultProfile (const std::string & itemTypeName) static
Get default profile for an item type.
Parameters
itemTypeName Item type name (e.g., "Food", "Weapon")
Returns
Default profile for the type, or empty profile if not found
Definition at line 104 of file ItemProfileManager.cpp.
References LoadProfile().
GetProfilesDirectory()
std::string ItemProfileManager::GetProfilesDirectory () static
Get profiles directory.
Returns
Profiles directory path
Definition at line 199 of file ItemProfileManager.cpp.
GetProfilesForType()
std::vector< ItemProfile > ItemProfileManager::GetProfilesForType (const std::string & itemTypeName) static
Get all profiles for an item type.
Parameters
itemTypeName Item type name
Returns
Vector of profiles for the type
Definition at line 111 of file ItemProfileManager.cpp.
References GetAllProfiles().
Initialize()
bool ItemProfileManager::Initialize (const std::string & profilesDir) static
Initialize the profile manager.
Parameters
profilesDir Directory containing profile files
Returns
True if initialization succeeded
Definition at line 21 of file ItemProfileManager.cpp.
Referenced by ItemGenerator::GenerateWithLLM().
LoadProfile()
ItemProfile ItemProfileManager::LoadProfile (const std::string & profileId) static
Load a profile from file.
Parameters
profileId Profile ID (filename without extension)
Returns
Loaded profile, or empty profile if not found
Definition at line 40 of file ItemProfileManager.cpp.
References LoadProfileFromPath().
Referenced by ItemGenerator::GenerateWithLLM(), and GetDefaultProfile().
LoadProfileFromPath()
ItemProfile ItemProfileManager::LoadProfileFromPath (const std::string & filePath) static
Load a profile from file path.
Parameters
filePath Full path to profile file
Returns
Loaded profile, or empty profile if failed
Definition at line 46 of file ItemProfileManager.cpp.
Referenced by GetAllProfiles(), and LoadProfile().
ProfileExists()
bool ItemProfileManager::ProfileExists (const std::string & profileId) static
Check if a profile exists.
Parameters
profileId Profile ID
Returns
True if profile exists
Definition at line 150 of file ItemProfileManager.cpp.
SaveProfile()
bool ItemProfileManager::SaveProfile (const ItemProfile & profile) static
Save a profile to file.
Parameters
profile Profile to save
Returns
True if save succeeded
Definition at line 75 of file ItemProfileManager.cpp.
References ItemProfile::id.
Referenced by CreateDefaultProfiles().
ValidateProfile()
bool ItemProfileManager::ValidateProfile (const ItemProfile & profile, std::vector< std::string > & errors) static
Validate a profile structure.
Parameters
profile Profile to validate
errors Output vector of error messages
Returns
True if profile is valid
Definition at line 166 of file ItemProfileManager.cpp.
References ItemProfile::fields, ItemProfile::id, and ItemProfile::itemTypeName.
The documentation for this class was generated from the following files:
RundeeItemFactory/RundeeItemFactory/include/Data/ItemProfileManager.h
RundeeItemFactory/RundeeItemFactory/src/Data/ItemProfileManager.cpp