RundeeItemFactory: ItemJsonWriter Class Reference
ItemJsonWriter Class Reference
Static class for writing item data to JSON files.
#include <ItemJsonWriter.h>
Static Public Member Functions
static bool WriteFoodToFile (const std::vector< ItemFoodData > &items, const std::string &path)
Write food items to JSON file (overwrites existing file).
static bool WriteDrinkToFile (const std::vector< ItemDrinkData > &items, const std::string &path)
Write drink items to JSON file (overwrites existing file).
static bool WriteMaterialToFile (const std::vector< ItemMaterialData > &items, const std::string &path)
Write material items to JSON file (overwrites existing file).
static bool WriteWeaponToFile (const std::vector< ItemWeaponData > &items, const std::string &path)
Write weapon items to JSON file (overwrites existing file).
static bool WriteWeaponComponentToFile (const std::vector< ItemWeaponComponentData > &items, const std::string &path)
Write weapon component items to JSON file (overwrites existing file).
static bool WriteAmmoToFile (const std::vector< ItemAmmoData > &items, const std::string &path)
Write ammo items to JSON file (overwrites existing file).
static bool MergeFoodToFile (const std::vector< ItemFoodData > &items, const std::string &path)
Merge food items with existing file (keeps existing, adds new, skips duplicates by ID).
static bool MergeDrinkToFile (const std::vector< ItemDrinkData > &items, const std::string &path)
Merge drink items with existing file.
static bool MergeMaterialToFile (const std::vector< ItemMaterialData > &items, const std::string &path)
Merge material items with existing file.
static bool MergeWeaponToFile (const std::vector< ItemWeaponData > &items, const std::string &path)
Merge weapon items with existing file.
static bool MergeWeaponComponentToFile (const std::vector< ItemWeaponComponentData > &items, const std::string &path)
Merge weapon component items with existing file.
static bool MergeAmmoToFile (const std::vector< ItemAmmoData > &items, const std::string &path)
Merge ammo items with existing file.
static std::set< std::string > GetExistingFoodIds (const std::string &path)
Get existing food item IDs from file (for avoiding duplicates).
static std::set< std::string > GetExistingDrinkIds (const std::string &path)
Get existing drink item IDs from file.
static std::set< std::string > GetExistingMaterialIds (const std::string &path)
Get existing material item IDs from file.
static std::set< std::string > GetExistingWeaponIds (const std::string &path)
Get existing weapon item IDs from file.
static std::set< std::string > GetExistingWeaponComponentIds (const std::string &path)
Get existing weapon component item IDs from file.
static std::set< std::string > GetExistingAmmoIds (const std::string &path)
Get existing ammo item IDs from file.
Detailed Description
Static class for writing item data to JSON files.
Provides type-specific methods for writing and merging items to JSON files. All methods handle file I/O, JSON serialization, and duplicate detection.
Definition at line 31 of file ItemJsonWriter.h.
Member Function Documentation
GetExistingAmmoIds()
std::set< std::string > ItemJsonWriter::GetExistingAmmoIds (const std::string & path) static
Get existing ammo item IDs from file.
Parameters
path JSON file path
Returns
Set of existing item IDs
Definition at line 809 of file ItemJsonWriter.cpp.
References ItemJsonParser::ParseAmmoFromJsonText().
Referenced by ItemGenerator::GenerateWithLLM(), and ProcessLLMResponse_Ammo().
GetExistingDrinkIds()
std::set< std::string > ItemJsonWriter::GetExistingDrinkIds (const std::string & path) static
Get existing drink item IDs from file.
Parameters
path JSON file path
Returns
Set of existing item IDs
Definition at line 398 of file ItemJsonWriter.cpp.
References ItemJsonParser::ParseDrinkFromJsonText().
Referenced by ItemGenerator::GenerateWithLLM(), and ProcessLLMResponse_Drink().
GetExistingFoodIds()
std::set< std::string > ItemJsonWriter::GetExistingFoodIds (const std::string & path) static
Get existing food item IDs from file (for avoiding duplicates).
Parameters
path JSON file path
Returns
Set of existing item IDs (empty set if file doesn't exist or is invalid)
Definition at line 372 of file ItemJsonWriter.cpp.
References ItemJsonParser::ParseFoodFromJsonText().
Referenced by ItemGenerator::GenerateWithLLM(), and ProcessLLMResponse_Food().
GetExistingMaterialIds()
std::set< std::string > ItemJsonWriter::GetExistingMaterialIds (const std::string & path) static
Get existing material item IDs from file.
Parameters
path JSON file path
Returns
Set of existing item IDs
Definition at line 424 of file ItemJsonWriter.cpp.
References ItemJsonParser::ParseMaterialFromJsonText().
Referenced by ItemGenerator::GenerateWithLLM(), and ProcessLLMResponse_Material().
GetExistingWeaponComponentIds()
std::set< std::string > ItemJsonWriter::GetExistingWeaponComponentIds (const std::string & path) static
Get existing weapon component item IDs from file.
Parameters
path JSON file path
Returns
Set of existing item IDs
Definition at line 700 of file ItemJsonWriter.cpp.
References ItemJsonParser::ParseWeaponComponentFromJsonText().
Referenced by ItemGenerator::GenerateWithLLM(), and ProcessLLMResponse_WeaponComponent().
GetExistingWeaponIds()
std::set< std::string > ItemJsonWriter::GetExistingWeaponIds (const std::string & path) static
Get existing weapon item IDs from file.
Parameters
path JSON file path
Returns
Set of existing item IDs
Definition at line 675 of file ItemJsonWriter.cpp.
References ItemJsonParser::ParseWeaponFromJsonText().
Referenced by ItemGenerator::GenerateWithLLM(), and ProcessLLMResponse_Weapon().
MergeAmmoToFile()
bool ItemJsonWriter::MergeAmmoToFile (const std::vector< ItemAmmoData > & items, const std::string & path) static
Merge ammo items with existing file.
Parameters
items Vector of new ammo items to merge
path JSON file path
Returns
true on success, false on failure
Definition at line 774 of file ItemJsonWriter.cpp.
References ItemJsonParser::ParseAmmoFromJsonText(), and WriteAmmoToFile().
MergeDrinkToFile()
bool ItemJsonWriter::MergeDrinkToFile (const std::vector< ItemDrinkData > & items, const std::string & path) static
Merge drink items with existing file.
Parameters
items Vector of new drink items to merge
path JSON file path
Returns
true on success, false on failure
Definition at line 252 of file ItemJsonWriter.cpp.
References ItemJsonParser::ParseDrinkFromJsonText(), and WriteDrinkToFile().
MergeFoodToFile()
bool ItemJsonWriter::MergeFoodToFile (const std::vector< ItemFoodData > & items, const std::string & path) static
Merge food items with existing file (keeps existing, adds new, skips duplicates by ID).
Parameters
items Vector of new food items to merge
path JSON file path (created if doesn't exist)
Returns
true on success, false on failure
Definition at line 192 of file ItemJsonWriter.cpp.
References ItemJsonParser::ParseFoodFromJsonText(), and WriteFoodToFile().
MergeMaterialToFile()
bool ItemJsonWriter::MergeMaterialToFile (const std::vector< ItemMaterialData > & items, const std::string & path) static
Merge material items with existing file.
Parameters
items Vector of new material items to merge
path JSON file path
Returns
true on success, false on failure
Definition at line 312 of file ItemJsonWriter.cpp.
References ItemJsonParser::ParseMaterialFromJsonText(), and WriteMaterialToFile().
MergeWeaponComponentToFile()
bool ItemJsonWriter::MergeWeaponComponentToFile (const std::vector< ItemWeaponComponentData > & items, const std::string & path) static
Merge weapon component items with existing file.
Parameters
items Vector of new weapon component items to merge
path JSON file path
Returns
true on success, false on failure
Definition at line 640 of file ItemJsonWriter.cpp.
References ItemJsonParser::ParseWeaponComponentFromJsonText(), and WriteWeaponComponentToFile().
MergeWeaponToFile()
bool ItemJsonWriter::MergeWeaponToFile (const std::vector< ItemWeaponData > & items, const std::string & path) static
Merge weapon items with existing file.
Parameters
items Vector of new weapon items to merge
path JSON file path
Returns
true on success, false on failure
Definition at line 605 of file ItemJsonWriter.cpp.
References ItemJsonParser::ParseWeaponFromJsonText(), and WriteWeaponToFile().
WriteAmmoToFile()
bool ItemJsonWriter::WriteAmmoToFile (const std::vector< ItemAmmoData > & items, const std::string & path) static
Write ammo items to JSON file (overwrites existing file).
Parameters
items Vector of ammo items to write
path Output file path
Returns
true on success, false on failure
Definition at line 725 of file ItemJsonWriter.cpp.
Referenced by MergeAmmoToFile(), and ProcessLLMResponse_Ammo().
WriteDrinkToFile()
bool ItemJsonWriter::WriteDrinkToFile (const std::vector< ItemDrinkData > & items, const std::string & path) static
Write drink items to JSON file (overwrites existing file).
Parameters
items Vector of drink items to write
path Output file path
Returns
true on success, false on failure
Definition at line 100 of file ItemJsonWriter.cpp.
Referenced by MergeDrinkToFile(), and ProcessLLMResponse_Drink().
WriteFoodToFile()
bool ItemJsonWriter::WriteFoodToFile (const std::vector< ItemFoodData > & items, const std::string & path) static
Write food items to JSON file (overwrites existing file).
Parameters
items Vector of food items to write
path Output file path
Returns
true on success, false on failure
Definition at line 54 of file ItemJsonWriter.cpp.
Referenced by MergeFoodToFile(), and ProcessLLMResponse_Food().
WriteMaterialToFile()
bool ItemJsonWriter::WriteMaterialToFile (const std::vector< ItemMaterialData > & items, const std::string & path) static
Write material items to JSON file (overwrites existing file).
Parameters
items Vector of material items to write
path Output file path
Returns
true on success, false on failure
Definition at line 146 of file ItemJsonWriter.cpp.
Referenced by MergeMaterialToFile(), and ProcessLLMResponse_Material().
WriteWeaponComponentToFile()
bool ItemJsonWriter::WriteWeaponComponentToFile (const std::vector< ItemWeaponComponentData > & items, const std::string & path) static
Write weapon component items to JSON file (overwrites existing file).
Parameters
items Vector of weapon component items to write
path Output file path
Returns
true on success, false on failure
Definition at line 519 of file ItemJsonWriter.cpp.
Referenced by MergeWeaponComponentToFile(), and ProcessLLMResponse_WeaponComponent().
WriteWeaponToFile()
bool ItemJsonWriter::WriteWeaponToFile (const std::vector< ItemWeaponData > & items, const std::string & path) static
Write weapon items to JSON file (overwrites existing file).
Parameters
items Vector of weapon items to write
path Output file path
Returns
true on success, false on failure
Definition at line 450 of file ItemJsonWriter.cpp.
Referenced by MergeWeaponToFile(), and ProcessLLMResponse_Weapon().
The documentation for this class was generated from the following files:
RundeeItemFactory/RundeeItemFactory/include/Writers/ItemJsonWriter.h
RundeeItemFactory/RundeeItemFactory/src/Writers/ItemJsonWriter.cpp