RundeeItemFactory: PromptTemplateLoader Class Reference
PromptTemplateLoader Class Reference
Static class for loading and processing prompt templates.
#include <PromptTemplateLoader.h>
Static Public Member Functions
static std::string LoadTemplate (const std::string &templateName, const std::string &presetContext, int maxHunger, int maxThirst, int count, const std::set< std::string > &excludeIds=std::set< std::string >(), const std::string &presetName="", const std::string &itemTypeName="", const std::string &modelName="", const std::string &generationTimestamp="", int existingCount=-1)
Load template from file and replace variables.
static std::string GetTemplateDirectory ()
Get the base directory for templates.
static bool TemplateExists (const std::string &templateName)
Check if template file exists.
Detailed Description
Static class for loading and processing prompt templates.
Loads prompt templates from external files and performs variable substitution. Templates are stored in the prompts/ directory relative to the executable.
Definition at line 25 of file PromptTemplateLoader.h.
Member Function Documentation
GetTemplateDirectory()
std::string PromptTemplateLoader::GetTemplateDirectory () static
Get the base directory for templates.
Returns the directory path where template files are stored. Typically: executable directory + "prompts/"
Returns
Template directory path
Definition at line 17 of file PromptTemplateLoader.cpp.
Referenced by LoadTemplate(), and TemplateExists().
LoadTemplate()
std::string PromptTemplateLoader::LoadTemplate (const std::string & templateName, const std::string & presetContext, int maxHunger, int maxThirst, int count, const std::set< std::string > & excludeIds = std::set<std::string>(), const std::string & presetName = "", const std::string & itemTypeName = "", const std::string & modelName = "", const std::string & generationTimestamp = "", int existingCount = -1) static
Load template from file and replace variables.
Loads a template file and replaces template variables with provided values. Template variables use syntax like {{VARIABLE_NAME}}.
Parameters
templateName Name of template file (without path, e.g., "food_template.txt")
presetContext World context/flavor text from preset
maxHunger Maximum hunger value for constraints
maxThirst Maximum thirst value for constraints
count Number of items to generate
excludeIds Set of existing item IDs to avoid duplicates
presetName Name of the preset being used
itemTypeName Name of the item type (e.g., "Food", "Weapon")
modelName LLM model name
generationTimestamp Timestamp of generation
existingCount Number of existing items
Returns
Processed template string with variables replaced, or empty string on error
Note
Template files are located in prompts/ directory relative to executable
Returns empty string if file not found or error occurs
Definition at line 45 of file PromptTemplateLoader.cpp.
References GetTemplateDirectory().
Referenced by DynamicPromptBuilder::BuildPromptFromProfile().
TemplateExists()
bool PromptTemplateLoader::TemplateExists (const std::string & templateName) static
Check if template file exists.
Verifies whether a template file exists in the template directory.
Parameters
templateName Name of template file to check
Returns
true if template exists, false otherwise
Definition at line 38 of file PromptTemplateLoader.cpp.
References GetTemplateDirectory().
The documentation for this class was generated from the following files:
RundeeItemFactory/RundeeItemFactory/include/Prompts/PromptTemplateLoader.h
RundeeItemFactory/RundeeItemFactory/src/Prompts/PromptTemplateLoader.cpp