RundeeItemFactory: PlayerProfileManager Namespace Reference
PlayerProfileManager Namespace Reference
Manager for loading player profiles.
Functions
PlayerProfile LoadProfile (const std::string &profileId, const std::string &profilesDir)
Load a player profile from file.
PlayerProfile LoadProfileFromPath (const std::string &filePath)
Load a player profile from file path.
PlayerProfile GetDefaultProfile (const std::string &profilesDir)
Get default player profile.
Detailed Description
Manager for loading player profiles.
Function Documentation
GetDefaultProfile()
PlayerProfile PlayerProfileManager::GetDefaultProfile (const std::string & profilesDir)
Get default player profile.
Parameters
profilesDir Directory containing player profile files
Returns
Default player profile (or empty if none found)
Definition at line 108 of file PlayerProfileManager.cpp.
References PlayerProfile::id, PlayerProfile::isDefault, and LoadProfileFromPath().
Referenced by ItemGenerator::GenerateWithLLM().
LoadProfile()
PlayerProfile PlayerProfileManager::LoadProfile (const std::string & profileId, const std::string & profilesDir)
Load a player profile from file.
Parameters
profileId Profile ID (filename without .json extension)
profilesDir Directory containing player profile files
Returns
Loaded player profile (empty if not found)
Definition at line 95 of file PlayerProfileManager.cpp.
References LoadProfileFromPath().
Referenced by ItemGenerator::GenerateWithLLM().
LoadProfileFromPath()
PlayerProfile PlayerProfileManager::LoadProfileFromPath (const std::string & filePath)
Load a player profile from file path.
Parameters
filePath Full path to profile JSON file
Returns
Loaded player profile (empty if not found)
Definition at line 19 of file PlayerProfileManager.cpp.
References PlayerProfile::description, PlayerStatField::description, PlayerStatSection::description, PlayerProfile::displayName, PlayerStatField::displayName, PlayerStatSection::displayName, PlayerStatField::displayOrder, PlayerStatSection::displayOrder, PlayerStatSection::fields, PlayerProfile::id, PlayerProfile::isDefault, PlayerSettings::maxEnergy, PlayerSettings::maxHealth, PlayerSettings::maxHunger, PlayerSettings::maxStamina, PlayerSettings::maxThirst, PlayerSettings::maxWeight, PlayerStatField::name, PlayerStatSection::name, PlayerProfile::playerSettings, PlayerProfile::statSections, PlayerStatField::value, and PlayerProfile::version.
Referenced by GetDefaultProfile(), and LoadProfile().