RundeeItemFactory: BalanceReporter Namespace Reference
BalanceReporter Namespace Reference
Classes
struct FoodStats
struct MaterialStats
struct WeaponStats
struct WeaponComponentStats
struct AmmoStats
Functions
int GenerateReport (const std::string &jsonFilePath, ItemType itemType)
static void PrintFoodReport (const std::vector< ItemFoodData > &items)
static void PrintDrinkReport (const std::vector< ItemDrinkData > &items)
static void PrintMaterialReport (const std::vector< ItemMaterialData > &items)
static void PrintWeaponReport (const std::vector< ItemWeaponData > &items)
static void PrintWeaponComponentReport (const std::vector< ItemWeaponComponentData > &items)
static void PrintAmmoReport (const std::vector< ItemAmmoData > &items)
Function Documentation
GenerateReport()
int BalanceReporter::GenerateReport (const std::string & jsonFilePath, ItemType itemType)
Definition at line 1040 of file BalanceReporter.cpp.
References Ammo, Drink, Food, Material, ItemJsonParser::ParseAmmoFromJsonText(), ItemJsonParser::ParseDrinkFromJsonText(), ItemJsonParser::ParseFoodFromJsonText(), ItemJsonParser::ParseMaterialFromJsonText(), ItemJsonParser::ParseWeaponComponentFromJsonText(), ItemJsonParser::ParseWeaponFromJsonText(), PrintAmmoReport(), PrintDrinkReport(), PrintFoodReport(), PrintMaterialReport(), PrintWeaponComponentReport(), PrintWeaponReport(), Weapon, and WeaponComponent.
Referenced by main().
PrintAmmoReport()
void BalanceReporter::PrintAmmoReport (const std::vector< ItemAmmoData > & items) static
Definition at line 893 of file BalanceReporter.cpp.
References BalanceReporter::AmmoStats::armorPiercingCount, BalanceReporter::AmmoStats::caliberCount, BalanceReporter::AmmoStats::count, BalanceReporter::AmmoStats::hollowPointCount, BalanceReporter::AmmoStats::incendiaryCount, BalanceReporter::AmmoStats::maxAccuracyBonus, BalanceReporter::AmmoStats::maxDamageBonus, BalanceReporter::AmmoStats::maxPenetration, BalanceReporter::AmmoStats::maxRecoilModifier, BalanceReporter::AmmoStats::maxValue, BalanceReporter::AmmoStats::minAccuracyBonus, BalanceReporter::AmmoStats::minDamageBonus, BalanceReporter::AmmoStats::minPenetration, BalanceReporter::AmmoStats::minRecoilModifier, BalanceReporter::AmmoStats::minValue, BalanceReporter::AmmoStats::rarityCount, BalanceReporter::AmmoStats::totalAccuracyBonus, BalanceReporter::AmmoStats::totalDamageBonus, BalanceReporter::AmmoStats::totalPenetration, BalanceReporter::AmmoStats::totalRecoilModifier, BalanceReporter::AmmoStats::totalValue, and BalanceReporter::AmmoStats::tracerCount.
Referenced by GenerateReport().
PrintDrinkReport()
void BalanceReporter::PrintDrinkReport (const std::vector< ItemDrinkData > & items) static
Definition at line 276 of file BalanceReporter.cpp.
References BalanceReporter::FoodStats::count, BalanceReporter::FoodStats::maxHealth, BalanceReporter::FoodStats::maxHunger, BalanceReporter::FoodStats::maxThirst, BalanceReporter::FoodStats::minHealth, BalanceReporter::FoodStats::minHunger, BalanceReporter::FoodStats::minThirst, BalanceReporter::FoodStats::rarityCount, BalanceReporter::FoodStats::spoilingCount, BalanceReporter::FoodStats::totalHealth, BalanceReporter::FoodStats::totalHunger, and BalanceReporter::FoodStats::totalThirst.
Referenced by GenerateReport().
PrintFoodReport()
void BalanceReporter::PrintFoodReport (const std::vector< ItemFoodData > & items) static
Definition at line 168 of file BalanceReporter.cpp.
References BalanceReporter::FoodStats::count, BalanceReporter::FoodStats::maxHealth, BalanceReporter::FoodStats::maxHunger, BalanceReporter::FoodStats::maxThirst, BalanceReporter::FoodStats::minHealth, BalanceReporter::FoodStats::minHunger, BalanceReporter::FoodStats::minThirst, BalanceReporter::FoodStats::rarityCount, BalanceReporter::FoodStats::spoilingCount, BalanceReporter::FoodStats::totalHealth, BalanceReporter::FoodStats::totalHunger, and BalanceReporter::FoodStats::totalThirst.
Referenced by GenerateReport().
PrintMaterialReport()
void BalanceReporter::PrintMaterialReport (const std::vector< ItemMaterialData > & items) static
Definition at line 373 of file BalanceReporter.cpp.
References BalanceReporter::MaterialStats::count, BalanceReporter::MaterialStats::materialTypeCount, BalanceReporter::MaterialStats::maxFlammability, BalanceReporter::MaterialStats::maxHardness, BalanceReporter::MaterialStats::maxValue, BalanceReporter::MaterialStats::minFlammability, BalanceReporter::MaterialStats::minHardness, BalanceReporter::MaterialStats::minValue, BalanceReporter::MaterialStats::rarityCount, BalanceReporter::MaterialStats::totalFlammability, BalanceReporter::MaterialStats::totalHardness, and BalanceReporter::MaterialStats::totalValue.
Referenced by GenerateReport().
PrintWeaponComponentReport()
void BalanceReporter::PrintWeaponComponentReport (const std::vector< ItemWeaponComponentData > & items) static
Definition at line 672 of file BalanceReporter.cpp.
References BalanceReporter::WeaponComponentStats::caliberCount, BalanceReporter::WeaponComponentStats::componentTypeCount, BalanceReporter::WeaponComponentStats::count, BalanceReporter::WeaponComponentStats::magazineCount, BalanceReporter::WeaponComponentStats::magazinesWithLoadPlan, BalanceReporter::WeaponComponentStats::magazineTypeCount, BalanceReporter::WeaponComponentStats::maxAccuracyModifier, BalanceReporter::WeaponComponentStats::maxDamageModifier, BalanceReporter::WeaponComponentStats::maxEffectiveRangeModifier, BalanceReporter::WeaponComponentStats::maxErgonomicsModifier, BalanceReporter::WeaponComponentStats::maxMagazineCapacity, BalanceReporter::WeaponComponentStats::maxMuzzleVelocityModifier, BalanceReporter::WeaponComponentStats::maxPenetrationModifier, BalanceReporter::WeaponComponentStats::maxRecoilModifier, BalanceReporter::WeaponComponentStats::maxWeightModifier, BalanceReporter::WeaponComponentStats::minAccuracyModifier, BalanceReporter::WeaponComponentStats::minDamageModifier, BalanceReporter::WeaponComponentStats::minEffectiveRangeModifier, BalanceReporter::WeaponComponentStats::minErgonomicsModifier, BalanceReporter::WeaponComponentStats::minMagazineCapacity, BalanceReporter::WeaponComponentStats::minMuzzleVelocityModifier, BalanceReporter::WeaponComponentStats::minPenetrationModifier, BalanceReporter::WeaponComponentStats::minRecoilModifier, BalanceReporter::WeaponComponentStats::minWeightModifier, BalanceReporter::WeaponComponentStats::mixedAmmoMagazineCount, BalanceReporter::WeaponComponentStats::rarityCount, BalanceReporter::WeaponComponentStats::totalAccuracyModifier, BalanceReporter::WeaponComponentStats::totalDamageModifier, BalanceReporter::WeaponComponentStats::totalEffectiveRangeModifier, BalanceReporter::WeaponComponentStats::totalErgonomicsModifier, BalanceReporter::WeaponComponentStats::totalMagazineCapacity, BalanceReporter::WeaponComponentStats::totalMuzzleVelocityModifier, BalanceReporter::WeaponComponentStats::totalPenetrationModifier, BalanceReporter::WeaponComponentStats::totalPlannedRounds, BalanceReporter::WeaponComponentStats::totalRecoilModifier, and BalanceReporter::WeaponComponentStats::totalWeightModifier.
Referenced by GenerateReport().
PrintWeaponReport()
void BalanceReporter::PrintWeaponReport (const std::vector< ItemWeaponData > & items) static
Definition at line 465 of file BalanceReporter.cpp.
References BalanceReporter::WeaponStats::caliberCount, BalanceReporter::WeaponStats::count, BalanceReporter::WeaponStats::maxAccuracy, BalanceReporter::WeaponStats::maxEffectiveRange, BalanceReporter::WeaponStats::maxErgonomics, BalanceReporter::WeaponStats::maxFireRate, BalanceReporter::WeaponStats::maxMaxDamage, BalanceReporter::WeaponStats::maxMinDamage, BalanceReporter::WeaponStats::maxModdingSlots, BalanceReporter::WeaponStats::maxMuzzleVelocity, BalanceReporter::WeaponStats::maxPenetrationPower, BalanceReporter::WeaponStats::maxRecoil, BalanceReporter::WeaponStats::maxWeight, BalanceReporter::WeaponStats::minAccuracy, BalanceReporter::WeaponStats::minEffectiveRange, BalanceReporter::WeaponStats::minErgonomics, BalanceReporter::WeaponStats::minFireRate, BalanceReporter::WeaponStats::minMaxDamage, BalanceReporter::WeaponStats::minMinDamage, BalanceReporter::WeaponStats::minModdingSlots, BalanceReporter::WeaponStats::minMuzzleVelocity, BalanceReporter::WeaponStats::minPenetrationPower, BalanceReporter::WeaponStats::minRecoil, BalanceReporter::WeaponStats::minWeight, BalanceReporter::WeaponStats::rarityCount, BalanceReporter::WeaponStats::totalAccuracy, BalanceReporter::WeaponStats::totalEffectiveRange, BalanceReporter::WeaponStats::totalErgonomics, BalanceReporter::WeaponStats::totalFireRate, BalanceReporter::WeaponStats::totalMaxDamage, BalanceReporter::WeaponStats::totalMinDamage, BalanceReporter::WeaponStats::totalModdingSlots, BalanceReporter::WeaponStats::totalMuzzleVelocity, BalanceReporter::WeaponStats::totalPenetrationPower, BalanceReporter::WeaponStats::totalRecoil, BalanceReporter::WeaponStats::totalWeight, BalanceReporter::WeaponStats::weaponCategoryCount, and BalanceReporter::WeaponStats::weaponTypeCount.
Referenced by GenerateReport().