RundeeItemFactory: CustomPresetManager Namespace Reference
CustomPresetManager Namespace Reference
Manager for custom preset operations.
Functions
bool LoadPresetFromFile (const std::string &filePath, CustomPreset &preset)
Load preset from JSON file.
bool SavePresetToFile (const CustomPreset &preset, const std::string &filePath)
Save preset to JSON file.
bool CreatePresetFromName (const std::string &presetName, CustomPreset &preset)
Create preset from built-in name.
bool ValidatePreset (const CustomPreset &preset, std::string &errorMessage)
Validate preset.
std::string GetPresetFlavorText (const CustomPreset &preset)
Get flavor text from preset.
Detailed Description
Manager for custom preset operations.
Function Documentation
CreatePresetFromName()
bool CustomPresetManager::CreatePresetFromName (const std::string & presetName, CustomPreset & preset)
Create preset from built-in name.
Parameters
presetName Name of built-in preset (e.g., "default")
preset Output preset
Returns
True if created successfully
Definition at line 193 of file CustomPreset.cpp.
References CustomPreset::author, CustomPreset::description, CustomPreset::displayName, CustomPreset::flavorText, CustomPreset::id, and CustomPreset::version.
GetPresetFlavorText()
std::string CustomPresetManager::GetPresetFlavorText (const CustomPreset & preset)
Get flavor text from preset.
Parameters
preset Preset
Returns
Flavor text string
Definition at line 128 of file CustomPreset.cpp.
References CustomPreset::flavorText.
LoadPresetFromFile()
bool CustomPresetManager::LoadPresetFromFile (const std::string & filePath, CustomPreset & preset)
Load preset from JSON file.
Parameters
filePath Path to preset JSON file
preset Output preset
Returns
True if loaded successfully
Definition at line 19 of file CustomPreset.cpp.
References CustomPreset::author, CustomPreset::description, CustomPreset::displayName, CustomPreset::flavorText, JsonUtils::GetStringSafe(), CustomPreset::id, CustomPreset::tags, ValidatePreset(), and CustomPreset::version.
SavePresetToFile()
bool CustomPresetManager::SavePresetToFile (const CustomPreset & preset, const std::string & filePath)
Save preset to JSON file.
Parameters
preset Preset to save
filePath Path to save to
Returns
True if saved successfully
Definition at line 79 of file CustomPreset.cpp.
References CustomPreset::author, CustomPreset::description, CustomPreset::displayName, CustomPreset::flavorText, CustomPreset::id, CustomPreset::tags, ValidatePreset(), and CustomPreset::version.
ValidatePreset()
bool CustomPresetManager::ValidatePreset (const CustomPreset & preset, std::string & errorMessage)
Validate preset.
Parameters
preset Preset to validate
errorMessage Output error message
Returns
True if valid
Definition at line 149 of file CustomPreset.cpp.
References CustomPreset::displayName, CustomPreset::flavorText, and CustomPreset::id.
Referenced by LoadPresetFromFile(), and SavePresetToFile().