RundeeItemFactory: StringUtils Namespace Reference
StringUtils Namespace Reference
Namespace for string utility functions.
Functions
void TrimString (std::string &str)
Trim whitespace from both ends of a string.
std::string CleanJsonArrayText (const std::string &input)
Clean JSON array text from LLM responses.
std::string FixCommonJsonErrors (const std::string &input)
Fix common JSON errors.
std::string EscapeForCmd (const std::string &s)
Escape special characters for command line.
std::string EscapeString (const std::string &s)
Escape string for JSON.
std::string NormalizeWhitespace (const std::string &s)
Normalize whitespace.
std::string StripAnsiEscapeCodes (const std::string &s)
Remove ANSI escape codes.
std::string RemoveControlCharacters (const std::string &s)
Remove non-printable control characters.
Detailed Description
Namespace for string utility functions.
Function Documentation
CleanJsonArrayText()
std::string StringUtils::CleanJsonArrayText (const std::string & input)
Clean JSON array text from LLM responses.
Removes trailing commas and closes unclosed brackets in JSON array text. Handles common JSON formatting errors from LLM responses.
Parameters
input Raw JSON text from LLM
Returns
Cleaned JSON text
Note
Removes trailing commas before closing brackets
Attempts to close unclosed brackets
Definition at line 118 of file StringUtils.cpp.
References FixCommonJsonErrors(), and TrimString().
Referenced by DynamicItemJsonParser::ParseItemsFromJsonText().
EscapeForCmd()
std::string StringUtils::EscapeForCmd (const std::string & s)
Escape special characters for command line.
Escapes special characters that have meaning in command line shells (quotes, spaces, etc.) so the string can be safely used in command line arguments.
Parameters
s String to escape
Returns
Escaped string safe for command line use
Definition at line 236 of file StringUtils.cpp.
EscapeString()
std::string StringUtils::EscapeString (const std::string & s)
Escape string for JSON.
Escapes special characters for JSON format (quotes, backslashes, newlines, etc.).
Parameters
s String to escape
Returns
JSON-escaped string
Definition at line 250 of file StringUtils.cpp.
FixCommonJsonErrors()
std::string StringUtils::FixCommonJsonErrors (const std::string & input)
Fix common JSON errors.
Attempts to fix common JSON formatting errors like trailing commas, unclosed brackets, and malformed structures.
Parameters
input JSON text with potential errors
Returns
Fixed JSON text
Definition at line 29 of file StringUtils.cpp.
Referenced by CleanJsonArrayText().
NormalizeWhitespace()
std::string StringUtils::NormalizeWhitespace (const std::string & s)
Normalize whitespace.
Replaces newlines and tabs with spaces, and collapses multiple spaces into one.
Parameters
s String to normalize
Returns
String with normalized whitespace
Definition at line 266 of file StringUtils.cpp.
RemoveControlCharacters()
std::string StringUtils::RemoveControlCharacters (const std::string & s)
Remove non-printable control characters.
Removes control characters (except whitespace) from the string. Preserves spaces, tabs, and newlines.
Parameters
s String potentially containing control characters
Returns
String with control characters removed
Definition at line 358 of file StringUtils.cpp.
StripAnsiEscapeCodes()
std::string StringUtils::StripAnsiEscapeCodes (const std::string & s)
Remove ANSI escape codes.
Removes ANSI escape sequences (e.g., cursor hide/show codes, color codes) from terminal output strings.
Parameters
s String potentially containing ANSI codes
Returns
String with ANSI codes removed
Definition at line 281 of file StringUtils.cpp.
TrimString()
void StringUtils::TrimString (std::string & str)
Trim whitespace from both ends of a string.
Removes leading and trailing whitespace characters (spaces, tabs, newlines). Modifies the string in-place.
Parameters
[in,out] str String to trim (modified in-place)
Definition at line 17 of file StringUtils.cpp.
Referenced by CleanJsonArrayText().