RundeeItemFactory: ItemGenerator Namespace Reference
ItemGenerator Namespace Reference
Main namespace for item generation functionality.
Functions
int GenerateWithLLM (const CommandLineArgs &args)
Generate items of a single type using LLM.
int GenerateBatch (const CommandLineArgs &args)
Generate multiple item types in batch mode.
int GenerateWithLLM_SingleBatch (const CommandLineArgs &args, const std::set< std::string > &existingIds, bool useCustomPreset, const CustomPreset &customPreset)
Detailed Description
Main namespace for item generation functionality.
Provides high-level functions to generate game items (Food, Drink, Material, Weapon, WeaponComponent, Ammo) using local LLM (Ollama) with quality checking and validation.
Function Documentation
GenerateBatch()
int ItemGenerator::GenerateBatch (const CommandLineArgs & args)
Generate multiple item types in batch mode.
Generates items for multiple types sequentially. Each item type is processed independently with its own output file (if specified) or default location.
Parameters
args Command line arguments containing batch configuration:
batchItems: Vector of BatchItem structures, each specifying:
itemType: Type of items to generate
count: Number of items to generate for this type
outputPath: Optional custom output path (empty uses default)
modelName: LLM model name (shared across all batch items)
preset: Preset type (shared across all batch items)
Returns
0 if all batch items succeeded, 1 if any failed
Note
Batch items are processed sequentially, not in parallel.
Each batch item can have its own output file or use default location.
See also
GenerateWithLLM for single item type generation
Definition at line 1922 of file ItemGenerator.cpp.
References CommandLineArgs::batchItems, FoodGenerateParams::count, GenerateWithLLM(), CommandLineParser::GetItemTypeName(), CommandLineArgs::itemType, LLM, CommandLineArgs::mode, FoodGenerateParams::outputPath, and CommandLineArgs::params.
Referenced by main().
GenerateWithLLM()
int ItemGenerator::GenerateWithLLM (const CommandLineArgs & args)
Generate items of a single type using LLM.
This function generates items of the specified type using the configured LLM model. It handles prompt building, LLM communication, JSON parsing, validation, quality checking, and file writing. Supports retry logic and quality-based regeneration.
Parameters
args Command line arguments containing generation parameters:
itemType: Type of items to generate (Food, Drink, Material, Weapon, WeaponComponent, Ammo)
count: Number of items to generate
modelName: LLM model name (e.g., "llama3", "mistral")
preset: Preset type (Default, Forest, Desert, Coast, City) or custom preset
outputPath: Path to output JSON file
params: Item-specific generation parameters (maxHunger, maxThirst, etc.)
Returns
0 on success, non-zero on failure
Note
The function automatically merges new items with existing items in the output file, skipping duplicates based on item ID.
See also
GenerateBatch for generating multiple item types in one operation
Definition at line 1531 of file ItemGenerator.cpp.
References Ammo, FoodGenerateParams::count, CommandLineArgs::customPresetPath, CustomPreset::displayName, Drink, Food, GenerateWithLLM_SingleBatch(), ItemJsonWriter::GetExistingAmmoIds(), ItemJsonWriter::GetExistingDrinkIds(), ItemJsonWriter::GetExistingFoodIds(), ItemJsonWriter::GetExistingMaterialIds(), ItemJsonWriter::GetExistingWeaponComponentIds(), ItemJsonWriter::GetExistingWeaponIds(), CommandLineParser::GetItemTypeName(), CustomPreset::id, CommandLineArgs::itemType, CustomPresetManager::LoadPresetFromFile(), LoadRegistryIds(), LogRegistryEvent(), Material, FoodGenerateParams::outputPath, CommandLineArgs::params, Weapon, and WeaponComponent.
Referenced by GenerateBatch(), and main().
GenerateWithLLM_SingleBatch()
int ItemGenerator::GenerateWithLLM_SingleBatch (const CommandLineArgs & args, const std::set< std::string > & existingIds, bool useCustomPreset, const CustomPreset & customPreset)
Definition at line 1808 of file ItemGenerator.cpp.
References CommandLineArgs::additionalPrompt, Ammo, PromptBuilder::BuildAmmoJsonPrompt(), PromptBuilder::BuildDrinkJsonPrompt(), PromptBuilder::BuildFoodJsonPrompt(), PromptBuilder::BuildMaterialJsonPrompt(), PromptBuilder::BuildWeaponComponentJsonPrompt(), PromptBuilder::BuildWeaponJsonPrompt(), FoodGenerateParams::count, Drink, Food, GetCurrentTimestamp(), CommandLineArgs::itemType, Material, CommandLineArgs::modelName, FoodGenerateParams::outputPath, CommandLineArgs::params, CommandLineArgs::preset, ProcessLLMResponse_Ammo(), ProcessLLMResponse_Drink(), ProcessLLMResponse_Food(), ProcessLLMResponse_Material(), ProcessLLMResponse_Weapon(), ProcessLLMResponse_WeaponComponent(), OllamaClient::RunWithRetry(), Weapon, and WeaponComponent.
Referenced by GenerateWithLLM().