RundeeItemFactory: QualityChecker Namespace Reference
QualityChecker Namespace Reference
Namespace for quality checking functions.
Classes
struct QualityResult
Result of a quality check operation.
Functions
QualityResult CheckWeaponQuality (const ItemWeaponData &item)
Check weapon item quality.
QualityResult CheckWeaponComponentQuality (const ItemWeaponComponentData &item)
Check weapon component item quality.
QualityResult CheckAmmoQuality (const ItemAmmoData &item)
Check ammo item quality.
QualityResult CheckFoodQuality (const ItemFoodData &item)
Check food item quality.
QualityResult CheckDrinkQuality (const ItemDrinkData &item)
Check drink item quality.
QualityResult CheckMaterialQuality (const ItemMaterialData &item)
Check material item quality.
void PrintQualityResult (const QualityResult &result, const std::string &itemId)
Print quality result to console.
Detailed Description
Namespace for quality checking functions.
Function Documentation
CheckAmmoQuality()
QualityResult QualityChecker::CheckAmmoQuality (const ItemAmmoData & item)
Check ammo item quality.
Validates ammo items for caliber consistency and stat balance.
Parameters
item Ammo item to check
Returns
QualityResult with validation results
Definition at line 223 of file QualityChecker.cpp.
References ItemAmmoData::armorPiercing, ItemAmmoData::caliber, ItemAmmoData::damageBonus, ItemAmmoData::hollowPoint, QualityChecker::QualityResult::isValid, ItemAmmoData::penetration, QualityChecker::QualityResult::qualityScore, ItemDataBase::rarity, ItemAmmoData::value, and QualityChecker::QualityResult::warnings.
Referenced by ProcessLLMResponse_Ammo().
CheckDrinkQuality()
QualityResult QualityChecker::CheckDrinkQuality (const ItemDrinkData & item)
Check drink item quality.
Validates drink items for restoration values and spoilage logic.
Parameters
item Drink item to check
Returns
QualityResult with validation results
Definition at line 329 of file QualityChecker.cpp.
References ItemDrinkData::healthRestore, ItemDrinkData::hungerRestore, QualityChecker::QualityResult::isValid, QualityChecker::QualityResult::qualityScore, ItemDrinkData::thirstRestore, and QualityChecker::QualityResult::warnings.
Referenced by ProcessLLMResponse_Drink().
CheckFoodQuality()
QualityResult QualityChecker::CheckFoodQuality (const ItemFoodData & item)
Check food item quality.
Validates food items for restoration values and spoilage logic.
Parameters
item Food item to check
Returns
QualityResult with validation results
Definition at line 283 of file QualityChecker.cpp.
References ItemFoodData::healthRestore, ItemFoodData::hungerRestore, QualityChecker::QualityResult::isValid, QualityChecker::QualityResult::qualityScore, ItemDataBase::rarity, ItemFoodData::spoils, ItemFoodData::spoilTimeMinutes, ItemFoodData::thirstRestore, and QualityChecker::QualityResult::warnings.
Referenced by ProcessLLMResponse_Food().
CheckMaterialQuality()
QualityResult QualityChecker::CheckMaterialQuality (const ItemMaterialData & item)
Check material item quality.
Validates material items for material properties and value balance.
Parameters
item Material item to check
Returns
QualityResult with validation results
Definition at line 362 of file QualityChecker.cpp.
References ItemMaterialData::flammability, ItemMaterialData::hardness, QualityChecker::QualityResult::isValid, QualityChecker::QualityResult::qualityScore, ItemMaterialData::value, and QualityChecker::QualityResult::warnings.
Referenced by ProcessLLMResponse_Material().
CheckWeaponComponentQuality()
QualityResult QualityChecker::CheckWeaponComponentQuality (const ItemWeaponComponentData & item)
Check weapon component item quality.
Validates weapon component items for compatibility and stat balance.
Parameters
item Weapon component item to check
Returns
QualityResult with validation results
Definition at line 145 of file QualityChecker.cpp.
References ItemWeaponComponentData::accuracyModifier, ItemWeaponComponentData::componentType, ItemWeaponComponentData::damageModifier, QualityChecker::QualityResult::errors, QualityChecker::QualityResult::isValid, ItemWeaponComponentData::magazineCapacity, ItemWeaponComponentData::penetrationModifier, QualityChecker::QualityResult::qualityScore, ItemDataBase::rarity, ItemWeaponComponentData::recoilModifier, QualityChecker::QualityResult::warnings, and ItemWeaponComponentData::weightModifier.
Referenced by ProcessLLMResponse_WeaponComponent().
CheckWeaponQuality()
QualityResult QualityChecker::CheckWeaponQuality (const ItemWeaponData & item)
Check weapon item quality.
Validates weapon items for realism, balance, and consistency. Checks combat stats, weapon type compatibility, and attachment slots.
Parameters
item Weapon item to check
Returns
QualityResult with validation results
Definition at line 25 of file QualityChecker.cpp.
References ItemWeaponData::accuracy, ItemWeaponData::attackSpeed, ItemWeaponData::caliber, ItemWeaponData::fireRate, QualityChecker::QualityResult::isValid, ItemWeaponData::maxDamage, ItemWeaponData::minDamage, ItemWeaponData::muzzleVelocity, QualityChecker::QualityResult::qualityScore, ItemDataBase::rarity, ItemWeaponData::reach, ItemWeaponData::recoil, QualityChecker::QualityResult::warnings, ItemWeaponData::weaponCategory, ItemWeaponData::weaponType, and ItemWeaponData::weight.
Referenced by ProcessLLMResponse_Weapon().
PrintQualityResult()
void QualityChecker::PrintQualityResult (const QualityResult & result, const std::string & itemId)
Print quality result to console.
Outputs the quality check results in a human-readable format. Shows warnings, errors, and quality score.
Parameters
result QualityResult to print
itemId Item ID for identification in output
Definition at line 388 of file QualityChecker.cpp.
References QualityChecker::QualityResult::errors, QualityChecker::QualityResult::qualityScore, and QualityChecker::QualityResult::warnings.
Referenced by ProcessLLMResponse_Ammo(), and ProcessLLMResponse_WeaponComponent().