RundeeItemFactory: CommandLineParser Namespace Reference
CommandLineParser Namespace Reference
Namespace for command line parsing utilities.
Functions
CommandLineArgs ParseArguments (int argc, char **argv)
Parse command line arguments.
std::vector< BatchItem > ParseBatchString (const std::string &batchStr)
Parse batch string into BatchItem vector.
std::string GetPresetName (PresetType preset)
Convert PresetType enum to string.
std::string GetItemTypeName (ItemType itemType)
Convert ItemType enum to string.
std::string GetRunModeName (RunMode mode)
Convert RunMode enum to string.
ItemType ParseItemType (const std::string &typeStr)
Convert string to ItemType enum.
Detailed Description
Namespace for command line parsing utilities.
Function Documentation
GetItemTypeName()
std::string CommandLineParser::GetItemTypeName (ItemType itemType)
Convert ItemType enum to string.
Parameters
itemType Item type enum value
Returns
String representation (e.g., "Food", "Weapon")
Definition at line 147 of file CommandLineParser.cpp.
References Ammo, Drink, Food, Material, Weapon, and WeaponComponent.
Referenced by ItemGenerator::GenerateBatch(), ItemGenerator::GenerateWithLLM(), and main().
GetPresetName()
std::string CommandLineParser::GetPresetName (PresetType preset)
Convert PresetType enum to string.
Parameters
preset Preset type enum value
Returns
String representation (e.g., "Default", "Forest")
Definition at line 135 of file CommandLineParser.cpp.
References City, Coast, Desert, and Forest.
Referenced by main().
GetRunModeName()
std::string CommandLineParser::GetRunModeName (RunMode mode)
Convert RunMode enum to string.
Parameters
mode Run mode enum value
Returns
String representation ("LLM" or "Batch")
Definition at line 161 of file CommandLineParser.cpp.
References Batch, and LLM.
Referenced by main().
ParseArguments()
CommandLineArgs CommandLineParser::ParseArguments (int argc, char ** argv)
Parse command line arguments.
Parses argc/argv into a CommandLineArgs structure. Supports:
Model selection: –model <name>
Item type: –type <food|drink|material|weapon|weaponcomponent|ammo>
Count: –count <number>
Preset: –preset <default|forest|desert|coast|city>
Output path: –output <path>
Batch mode: –batch <type1:count1,type2:count2,...>
Custom preset: –custom-preset <path>
Additional prompt: –additional-prompt <text>
Parameters
argc Number of command line arguments
argv Array of command line argument strings
Returns
Parsed CommandLineArgs structure
Definition at line 19 of file CommandLineParser.cpp.
References CommandLineArgs::additionalPrompt, Ammo, Batch, CommandLineArgs::batchItems, City, Coast, FoodGenerateParams::count, CommandLineArgs::customPresetPath, Default, Desert, Drink, Food, Forest, CommandLineArgs::itemType, LLM, Material, FoodGenerateParams::maxHunger, FoodGenerateParams::maxThirst, CommandLineArgs::mode, CommandLineArgs::modelName, FoodGenerateParams::outputPath, CommandLineArgs::params, ParseBatchString(), CommandLineArgs::preset, CommandLineArgs::reportPath, Weapon, and WeaponComponent.
Referenced by main().
ParseBatchString()
std::vector< BatchItem > CommandLineParser::ParseBatchString (const std::string & batchStr)
Parse batch string into BatchItem vector.
Parses a comma-separated batch string like "food:10,weapon:5,ammo:20" into a vector of BatchItem structures.
Parameters
batchStr Batch string in format "type1:count1,type2:count2,..."
Returns
Vector of BatchItem structures
Note
Item type names are case-insensitive
Invalid item types are skipped with a warning
Definition at line 192 of file CommandLineParser.cpp.
References BatchItem::count, BatchItem::itemType, BatchItem::outputPath, and ParseItemType().
Referenced by ParseArguments().
ParseItemType()
ItemType CommandLineParser::ParseItemType (const std::string & typeStr)
Convert string to ItemType enum.
Parses a string (case-insensitive) into an ItemType enum value.
Parameters
typeStr String representation of item type
Returns
ItemType enum value, or ItemType::Food if parsing fails
Note
Valid strings: "food", "drink", "material", "weapon", "weaponcomponent", "ammo"
Definition at line 171 of file CommandLineParser.cpp.
References Ammo, Drink, Food, Material, Weapon, and WeaponComponent.
Referenced by ParseBatchString().