// ===============================
// Project Name: RundeeItemFactory
// File Name: ItemMaterialData.h
// Author: Haneul Lee (Rundee)
// Created Date: 2025-11-15
// Description: Data structure for material / junk items generated by LLM.
// ===============================
// Copyright (c) 2025 Haneul Lee. All rights reserved.
// ===============================

#pragma once

#include "Data/ItemDataBase.h"

struct ItemMaterialData : public ItemDataBase
{
    // Material-specific properties
    std::string materialType;  // "Wood", "Metal", "Plastic", "Fabric", "Glass", "Electronic", etc.
    int hardness = 0;          // 0-100, structural strength
    int flammability = 0;      // 0-100, how well it burns
    int value = 0;             // 0-100, scrap / trade value

    // Override base class method
    std::string GetItemTypeName() const override { return "Material"; }
};