/**
 * @file ItemMaterialData.h
 * @brief Data structure for material / junk items generated by LLM
 * @author Haneul Lee (Rundee)
 * @date 2025-11-15
 * @copyright Copyright (c) 2025 Haneul Lee. All rights reserved.
 * 
 * Defines the data structure for material items used in crafting and trading.
 * Includes material properties like hardness, flammability, and trade value.
 */

#pragma once

#include "Data/ItemDataBase.h"

/**
 * @struct ItemMaterialData
 * @brief Data structure representing a material item
 * 
 * Contains properties specific to material items, including material type,
 * physical properties, and trade value. Used for crafting resources and junk items.
 */
struct ItemMaterialData : public ItemDataBase
{
    /**
     * @brief Material type identifier
     * 
     * Examples: "Wood", "Metal", "Plastic", "Fabric", "Glass", "Electronic", etc.
     * Used for crafting recipes and material compatibility.
     */
    std::string materialType;

    /**
     * @brief Structural strength (0-100)
     * 
     * Higher values indicate stronger materials. Affects durability and
     * suitability for structural crafting.
     */
    int hardness = 0;

    /**
     * @brief Flammability rating (0-100)
     * 
     * Higher values indicate more flammable materials. Affects fire behavior
     * and combustion properties.
     */
    int flammability = 0;

    /**
     * @brief Trade/scrap value (0-100)
     * 
     * Economic value of the material. Used for trading and scrap calculations.
     */
    int value = 0;

    /**
     * @brief Get the item type name
     * @return Always returns "Material"
     */
    std::string GetItemTypeName() const override { return "Material"; }
};